-- Open Task claim mutation. Approved architecture: Option B (SECURITY
-- DEFINER RPC), not a new RLS UPDATE policy.
--
--   - Lives in `public`, not `internal`, because that's where the one
--     other client-callable RPC in this codebase already lives
--     (redeem_household_invite, 20260706120000_household_invites.sql).
--     `internal` stays reserved for RLS-policy-only helpers
--     (is_household_member, shares_household_with) that are never called
--     directly by client code — there is no public-wrapper/internal-impl
--     split here, matching that existing precedent exactly.
--   - Column-scoping is structural, not policy-based: the function
--     accepts only p_task_id, so there is no payload shape through which
--     a caller could smuggle a change to status/points/title alongside
--     the claim — unlike a plain RLS-gated UPDATE, which can only
--     restrict which *rows* are writable, not which *columns* a given
--     request touches.
--   - Failure reporting follows the existing RAISE EXCEPTION + ERRCODE
--     convention (matching redeem_household_invite) rather than a new
--     discriminated-result-row shape. Only "already claimed" gets a
--     dedicated code (CH001 — project-specific, not a standard Postgres
--     class) because it's the one outcome the product needs a specific
--     message for; every other failure stays generic and unmapped, the
--     same way redeem_household_invite's not-found/expired/revoked cases
--     all collapse to one generic message today (copy.householdJoin.error).
--   - Race safety comes from the single conditional UPDATE's WHERE clause
--     (compare-and-swap on assignee_profile_id IS NULL) — no preceding
--     SELECT ... FOR UPDATE lock, no advisory locks; none are needed.
--
-- Out of scope, deliberately, and must stay that way: this function must
-- never be extended to complete a task, award points, or create a
-- ContributionClaim. Claiming an open task only ever means accepting
-- responsibility for it — nothing else.
--
-- Migration history rule: do not edit this file after it is applied.

CREATE OR REPLACE FUNCTION public.claim_open_task(p_task_id uuid)
RETURNS tasks
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_caller uuid := auth.uid();
  v_task   tasks%ROWTYPE;
BEGIN
  IF v_caller IS NULL THEN
    RAISE EXCEPTION 'Not authenticated' USING ERRCODE = '28000';
  END IF;

  SELECT * INTO v_task FROM tasks WHERE id = p_task_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Task not found' USING ERRCODE = 'P0002';
  END IF;

  -- Any household role may claim (tasks.claim_open is granted to child and
  -- up), so plain membership is the whole check — no role list needed.
  IF NOT internal.is_household_member(v_task.household_id, v_caller) THEN
    RAISE EXCEPTION 'Not a member of this task''s household' USING ERRCODE = '28000';
  END IF;

  UPDATE tasks
  SET assignee_profile_id = v_caller
  WHERE id = p_task_id
    AND assignee_profile_id IS NULL
    AND status <> 'completed'
  RETURNING * INTO v_task;

  IF NOT FOUND THEN
    -- Either already assigned, or lost a race that opened between the
    -- SELECT above and this UPDATE — both are "already claimed" from the
    -- caller's point of view.
    RAISE EXCEPTION 'Task already claimed' USING ERRCODE = 'CH001';
  END IF;

  RETURN v_task;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.claim_open_task(uuid) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION public.claim_open_task(uuid) TO authenticated;
