-- Adds an explicit date-only/timed discriminator for tasks.due_at.
-- Phase 2 (task configuration fields) — P2-D03/P2-D04/P2-D09 (Final
-- Pre-Execution Determination, V6 existing-data evidence: authoritative
-- query confirmed tasks_with_due_at = 0 prior to this migration).
--
-- Why this column exists: due_at is a single timestamptz. A date-only
-- entry ("15 Aug 2026") and a timed entry that happens to land on an
-- exact UTC-midnight instant (e.g. a user at UTC+03 entering 03:00
-- local) can serialize to the byte-identical timestamptz value. Without
-- a separate bit, "was a time explicitly chosen" cannot be reconstructed
-- from due_at alone for every valid input — demonstrated directly during
-- planning validation, not assumed. due_at_has_time is written once, at
-- task creation, alongside due_at, from the one place that genuinely
-- knows the answer (the creation-form picker interaction) — it is never
-- inferred from due_at's shape.
--
-- Semantics:
--   due_at IS NULL                       -> due_at_has_time is NULL (no due date; irrelevant)
--   due_at IS NOT NULL, due_at_has_time = false -> DATE_ONLY (all-day)
--   due_at IS NOT NULL, due_at_has_time = true  -> DATE_WITH_TIME (timed)
--
-- No DEFAULT is set (neither true nor false): a default would silently
-- assert an unproven semantic for any row it applies to. This column is
-- populated explicitly by application code at insert time only. No
-- backfill is performed — the pre-migration existing-data query proved
-- zero rows have due_at IS NOT NULL, so there is no historical row to
-- classify.
--
-- Migration history rule: do not edit this file after it is applied.

ALTER TABLE tasks
  ADD COLUMN due_at_has_time boolean NULL;

COMMENT ON COLUMN tasks.due_at_has_time IS
  'Discriminator for due_at: true = user supplied an explicit time (date+time), false = date-only (all-day), NULL = due_at itself is NULL. Never inferred from due_at''s value — always written explicitly at creation time.';
