-- T1.9.1: Household invite links + emoji avatar support
--
-- Scope: household_invites table, avatar_emoji column on profiles, and a
-- SECURITY DEFINER RPC (redeem_household_invite) letting a freshly
-- authenticated user (including an anonymous-auth session) join a
-- household by code without first being a member of it.
--
-- Does not touch tasks/rewards/points_balances RLS. Does not add a
-- household_members INSERT policy for the normal (non-invite) join path —
-- that remains separate, pre-existing scope (T1.4.5 in docs/roadmap.md).
--
-- Migration history rule: do not edit this file after it is applied.

-- ============================================================
-- profiles: avatar_emoji
-- ============================================================
-- Alternative to avatar_url — a single emoji character used as a
-- lightweight avatar. Display precedence (avatar_url vs avatar_emoji vs
-- initials fallback) is an app-layer concern, not enforced here.
ALTER TABLE profiles ADD COLUMN avatar_emoji text NULL;

-- ============================================================
-- household_invites
-- ============================================================
CREATE TABLE household_invites (
  id                    uuid                  PRIMARY KEY DEFAULT gen_random_uuid(),
  household_id          uuid                  NOT NULL REFERENCES households (id) ON DELETE CASCADE,
  code                  text                  NOT NULL,
  role                  household_member_role NOT NULL DEFAULT 'child',
  created_by_profile_id uuid                  NOT NULL REFERENCES profiles (id) ON DELETE RESTRICT,
  redemption_count      integer               NOT NULL DEFAULT 0,
  revoked_at            timestamptz           NULL,
  expires_at            timestamptz           NOT NULL DEFAULT (now() + interval '30 days'),
  created_at            timestamptz           NOT NULL DEFAULT now(),

  CONSTRAINT uq_household_invites_code UNIQUE (code),
  CONSTRAINT chk_household_invites_redemption_count_non_negative CHECK (redemption_count >= 0),
  -- An invite can never mint another owner — 'owner' is set only at
  -- household creation (createHouseholdWithOwner).
  CONSTRAINT chk_household_invites_role_not_owner CHECK (role <> 'owner')
);

CREATE INDEX idx_household_invites_household ON household_invites (household_id);

ALTER TABLE household_invites ENABLE ROW LEVEL SECURITY;

-- Management (create/view/revoke) is owner/admin-only, reusing the same
-- SECURITY DEFINER helper from 20260704000000_contribution_claims_rls.sql.
CREATE POLICY household_invites_select_household_admin
ON household_invites
FOR SELECT
TO authenticated
USING (
  internal.is_household_member(household_id, auth.uid(), ARRAY['owner','admin']::household_member_role[])
);

CREATE POLICY household_invites_insert_household_admin
ON household_invites
FOR INSERT
TO authenticated
WITH CHECK (
  created_by_profile_id = auth.uid()
  AND internal.is_household_member(household_id, auth.uid(), ARRAY['owner','admin']::household_member_role[])
);

-- Revocation is the only supported update (set revoked_at); enforced at
-- the app layer, not restricted further here since WITH CHECK re-runs the
-- same admin-membership condition regardless of which column changed.
CREATE POLICY household_invites_update_household_admin
ON household_invites
FOR UPDATE
TO authenticated
USING (
  internal.is_household_member(household_id, auth.uid(), ARRAY['owner','admin']::household_member_role[])
)
WITH CHECK (
  internal.is_household_member(household_id, auth.uid(), ARRAY['owner','admin']::household_member_role[])
);

-- No DELETE policy: invites are revoked (revoked_at), never deleted —
-- preserves an audit trail of who invited whom.

-- ============================================================
-- redeem_household_invite (SECURITY DEFINER RPC)
-- ============================================================
--
-- The redeeming caller is, by definition, not yet a household member, so
-- the SELECT policy above (owner/admin only) would always deny them read
-- access to household_invites, and no INSERT policy exists for
-- household_members at all yet. This function is the single, narrow,
-- server-validated path that performs both writes after checking the
-- invite's validity itself — the caller never touches household_invites
-- or household_members directly for redemption.
--
-- Always acts on auth.uid() — never accepts a target profile id — so a
-- caller can only ever redeem an invite for themselves.
--
-- profiles upsert uses DO NOTHING, not DO UPDATE: if the caller already
-- has a profile (e.g. redeeming a second household's invite), their
-- existing display_name/avatar_emoji is left untouched — this RPC's
-- p_display_name/p_avatar_emoji are for first-time profile creation only,
-- not a backdoor to edit an existing profile.
CREATE OR REPLACE FUNCTION public.redeem_household_invite(
  p_code         text,
  p_display_name text,
  p_avatar_emoji text DEFAULT NULL
) RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_invite household_invites%ROWTYPE;
  v_caller uuid := auth.uid();
BEGIN
  IF v_caller IS NULL THEN
    RAISE EXCEPTION 'Not authenticated' USING ERRCODE = '28000';
  END IF;

  IF p_display_name IS NULL OR btrim(p_display_name) = '' THEN
    RAISE EXCEPTION 'Display name is required' USING ERRCODE = '22023';
  END IF;

  SELECT * INTO v_invite
  FROM household_invites
  WHERE code = p_code
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Invite not found' USING ERRCODE = 'P0002';
  END IF;

  IF v_invite.revoked_at IS NOT NULL THEN
    RAISE EXCEPTION 'Invite has been revoked' USING ERRCODE = '28000';
  END IF;

  IF v_invite.expires_at < now() THEN
    RAISE EXCEPTION 'Invite has expired' USING ERRCODE = '28000';
  END IF;

  INSERT INTO profiles (id, display_name, avatar_emoji)
  VALUES (v_caller, btrim(p_display_name), p_avatar_emoji)
  ON CONFLICT (id) DO NOTHING;

  -- Idempotent: redeeming the same invite twice (retry, duplicate tap)
  -- does not duplicate membership or double-count redemption_count below.
  INSERT INTO household_members (household_id, profile_id, role)
  VALUES (v_invite.household_id, v_caller, v_invite.role)
  ON CONFLICT (household_id, profile_id) DO NOTHING;

  UPDATE household_invites
  SET redemption_count = redemption_count + 1
  WHERE id = v_invite.id;

  RETURN v_invite.household_id;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.redeem_household_invite(text, text, text) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION public.redeem_household_invite(text, text, text) TO authenticated;
