-- Rewards Redemption — Slice 2: request/approve/reject RPCs.
--
-- Every mutation of reward_redemptions and every points-moving operation
-- here goes through these three SECURITY DEFINER functions — the prior
-- migration leaves no other client-write path to either table for this
-- feature (reward_redemptions has no INSERT/UPDATE/DELETE grant or RLS
-- write policy at all; points_balances/point_transactions never did).
--
-- Hardening, uniform with every existing RPC in this schema
-- (claim_open_task, complete_task, approve/reject_task_completion,
-- request_task_completion): SECURITY DEFINER, SET search_path = public,
-- auth.uid() derived server-side with a NULL-caller guard, REVOKE EXECUTE
-- FROM PUBLIC + GRANT to authenticated only. Additionally hardened beyond
-- that existing baseline (approved in the Final Authorization Closure):
-- every table/function reference below is fully schema-qualified
-- (public.rewards, public.reward_redemptions, public.points_balances,
-- public.point_transactions, internal.is_household_member), not left to
-- search_path resolution alone.
--
-- Migration history rule: do not edit this file after it is applied.

-- ============================================================
-- request_reward_redemption
-- ============================================================
--
-- Only reward_id and client_request_id are trusted as client input.
-- Household, role, reward eligibility, balance, and the persisted price
-- snapshot are all derived/verified server-side — never client-supplied.
--
-- Sequence: idempotency fast-path (optimization only, not the
-- concurrency boundary) -> lock+read the reward row (FOR SHARE) ->
-- verify ACTIVE -> verify exact child role in the reward's own household
-- -> lock+read the balance row (FOR SHARE) -> Decision 9 -> attempt the
-- insert -> on a uniqueness conflict, resolve by re-deriving from actual
-- row data (Decision 10 takes semantic precedence over Decision 8
-- regardless of which named constraint Postgres happens to report first
-- for a given conflicting insert).
CREATE OR REPLACE FUNCTION public.request_reward_redemption(
  p_reward_id         uuid,
  p_client_request_id uuid
)
RETURNS public.reward_redemptions
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_caller           uuid := auth.uid();
  v_existing         public.reward_redemptions%ROWTYPE;
  v_reward_household uuid;
  v_reward_status    reward_status;
  v_reward_price     integer;
  v_balance          integer;
  v_redemption       public.reward_redemptions%ROWTYPE;
BEGIN
  IF v_caller IS NULL THEN
    RAISE EXCEPTION 'Not authenticated' USING ERRCODE = '28000';
  END IF;

  -- Fast-path replay optimization only — the permanent unique
  -- constraint below is the actual authoritative boundary. This early
  -- return only saves round trips for the common repeated-poll case; it
  -- is safe regardless of concurrent activity because the exception
  -- handler at the bottom re-derives the same answer if this check
  -- loses a race against a concurrent identical request.
  SELECT * INTO v_existing
  FROM public.reward_redemptions
  WHERE requested_by_profile_id = v_caller
    AND client_request_id = p_client_request_id;

  IF FOUND THEN
    IF v_existing.reward_id = p_reward_id THEN
      RETURN v_existing;
    ELSE
      RAISE EXCEPTION 'client_request_id already used for a different reward' USING ERRCODE = 'CH010';
    END IF;
  END IF;

  SELECT household_id, status, points_required
    INTO v_reward_household, v_reward_status, v_reward_price
  FROM public.rewards
  WHERE id = p_reward_id
  FOR SHARE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Reward not found' USING ERRCODE = 'CH006';
  END IF;

  IF v_reward_status <> 'active' THEN
    RAISE EXCEPTION 'Reward is not active' USING ERRCODE = 'CH007';
  END IF;

  IF NOT internal.is_household_member(
    v_reward_household, v_caller, ARRAY['child']::household_member_role[]
  ) THEN
    RAISE EXCEPTION 'Not authorized to request this reward' USING ERRCODE = '28000';
  END IF;

  SELECT balance INTO v_balance
  FROM public.points_balances
  WHERE household_id = v_reward_household
    AND profile_id   = v_caller
  FOR SHARE;

  IF NOT FOUND THEN
    v_balance := 0;
  END IF;

  IF v_balance < v_reward_price THEN
    RAISE EXCEPTION 'Insufficient balance to request this reward' USING ERRCODE = 'CH008';
  END IF;

  BEGIN
    INSERT INTO public.reward_redemptions
      (household_id, reward_id, requested_by_profile_id, client_request_id, points_required_snapshot)
    VALUES
      (v_reward_household, p_reward_id, v_caller, p_client_request_id, v_reward_price)
    RETURNING * INTO v_redemption;

    RETURN v_redemption;
  EXCEPTION WHEN unique_violation THEN
    -- Decision 10 has semantic precedence over Decision 8. Re-derive the
    -- outcome from actual row data rather than from which constraint's
    -- name happened to appear in this exception — correct regardless of
    -- Postgres's internal check ordering for this specific conflict.
    SELECT * INTO v_existing
    FROM public.reward_redemptions
    WHERE requested_by_profile_id = v_caller
      AND client_request_id = p_client_request_id;

    IF FOUND THEN
      IF v_existing.reward_id = p_reward_id THEN
        RETURN v_existing;
      ELSE
        RAISE EXCEPTION 'client_request_id already used for a different reward' USING ERRCODE = 'CH010';
      END IF;
    ELSE
      -- No row matches this idempotency key, so the violation must have
      -- been Decision 8's one-pending-per-(child,reward) constraint.
      RAISE EXCEPTION 'A pending redemption already exists for this reward' USING ERRCODE = 'CH011';
    END IF;
  END;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.request_reward_redemption(uuid, uuid) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION public.request_reward_redemption(uuid, uuid) TO authenticated;

-- ============================================================
-- approve_reward_redemption
-- ============================================================
--
-- A points_balances row is guaranteed to already exist for the
-- requester by the time a redemption reaches approval: Decision 9
-- required balance >= a strictly positive price at request time
-- (chk_reward_redemptions_points_positive), so no upsert is needed here
-- — a plain conditional UPDATE is sufficient, unlike complete_task's
-- upsert (which must handle a genuinely first-ever award).
--
-- Atomicity: the redemption-status CAS, the reward-status check, the
-- balance deduction, and the ledger insert all live in one function
-- body with no internal COMMIT — an insufficient-balance RAISE EXCEPTION
-- aborts the whole transaction, so the redemption-status CAS a few
-- lines above is rolled back too, leaving the redemption PENDING
-- exactly per Decision 5, not merely "unapproved."
CREATE OR REPLACE FUNCTION public.approve_reward_redemption(
  p_redemption_id uuid
)
RETURNS public.reward_redemptions
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_caller        uuid := auth.uid();
  v_redemption    public.reward_redemptions%ROWTYPE;
  v_reward_status reward_status;
  v_new_balance   integer;
BEGIN
  IF v_caller IS NULL THEN
    RAISE EXCEPTION 'Not authenticated' USING ERRCODE = '28000';
  END IF;

  SELECT * INTO v_redemption
  FROM public.reward_redemptions
  WHERE id = p_redemption_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Redemption not found' USING ERRCODE = 'CH012';
  END IF;

  IF NOT internal.is_household_member(
    v_redemption.household_id, v_caller, ARRAY['owner','admin','adult']::household_member_role[]
  ) THEN
    RAISE EXCEPTION 'Not authorized to approve this redemption' USING ERRCODE = '28000';
  END IF;

  SELECT status INTO v_reward_status
  FROM public.rewards
  WHERE id = v_redemption.reward_id
  FOR SHARE;

  IF v_reward_status IS DISTINCT FROM 'active' THEN
    RAISE EXCEPTION 'Reward is no longer active' USING ERRCODE = 'CH007';
  END IF;

  UPDATE public.reward_redemptions
  SET status                 = 'approved',
      reviewed_by_profile_id = v_caller,
      reviewed_at            = now(),
      updated_at              = now()
  WHERE id = p_redemption_id
    AND status = 'pending'
  RETURNING * INTO v_redemption;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Redemption is not pending review' USING ERRCODE = 'CH013';
  END IF;

  UPDATE public.points_balances
  SET balance    = balance - v_redemption.points_required_snapshot,
      updated_at = now()
  WHERE household_id = v_redemption.household_id
    AND profile_id    = v_redemption.requested_by_profile_id
    AND balance       >= v_redemption.points_required_snapshot
  RETURNING balance INTO v_new_balance;

  IF NOT FOUND THEN
    -- Aborts the whole transaction — the status CAS above is rolled
    -- back with it, so the redemption ends this call still PENDING,
    -- per Decision 5.
    RAISE EXCEPTION 'Insufficient balance to approve this redemption' USING ERRCODE = 'CH009';
  END IF;

  INSERT INTO public.point_transactions
    (household_id, profile_id, type, amount, balance_after, reward_id, reward_redemption_id, created_by_profile_id)
  VALUES
    (v_redemption.household_id, v_redemption.requested_by_profile_id, 'reward_redemption',
     -v_redemption.points_required_snapshot, v_new_balance, v_redemption.reward_id, v_redemption.id, v_caller);

  RETURN v_redemption;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.approve_reward_redemption(uuid) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION public.approve_reward_redemption(uuid) TO authenticated;

-- ============================================================
-- reject_reward_redemption
-- ============================================================
--
-- No reward-row lock needed — no economic decision depends on reward
-- state for a rejection. No balance or ledger mutation at all.
CREATE OR REPLACE FUNCTION public.reject_reward_redemption(
  p_redemption_id uuid
)
RETURNS public.reward_redemptions
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_caller     uuid := auth.uid();
  v_redemption public.reward_redemptions%ROWTYPE;
BEGIN
  IF v_caller IS NULL THEN
    RAISE EXCEPTION 'Not authenticated' USING ERRCODE = '28000';
  END IF;

  SELECT * INTO v_redemption
  FROM public.reward_redemptions
  WHERE id = p_redemption_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Redemption not found' USING ERRCODE = 'CH012';
  END IF;

  IF NOT internal.is_household_member(
    v_redemption.household_id, v_caller, ARRAY['owner','admin','adult']::household_member_role[]
  ) THEN
    RAISE EXCEPTION 'Not authorized to reject this redemption' USING ERRCODE = '28000';
  END IF;

  UPDATE public.reward_redemptions
  SET status                 = 'rejected',
      reviewed_by_profile_id = v_caller,
      reviewed_at            = now(),
      updated_at              = now()
  WHERE id = p_redemption_id
    AND status = 'pending'
  RETURNING * INTO v_redemption;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Redemption is not pending review' USING ERRCODE = 'CH013';
  END IF;

  RETURN v_redemption;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.reject_reward_redemption(uuid) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION public.reject_reward_redemption(uuid) TO authenticated;
