-- T1.4.4: Initial Schema Migration
-- ChoreHero — baseline schema
--
-- Scope: enums, tables, PKs, FKs, indexes, constraints, RLS enabled.
-- NOT included: RLS policies, helper functions, RPCs, triggers, seed data.
-- RLS policies will be added in T1.4.5.
--
-- FK ON DELETE behavior is explicit on every foreign key.
-- Migration history rule: do not edit this file after it is applied.

-- ============================================================
-- ENUMS
-- ============================================================

CREATE TYPE household_member_role AS ENUM (
  'owner',   -- created the household; full control
  'admin',   -- trusted adult with management rights
  'adult',   -- standard adult member; can approve requests
  'child'    -- limited permissions; cannot create tasks for adults directly
);

-- Task statuses represent observable workflow states, not user intentions.
-- 'accepted' is intentionally excluded from this enum.
CREATE TYPE task_status AS ENUM (
  'open',
  'in_progress',
  'needs_attention',
  'completed'
);

CREATE TYPE reward_status AS ENUM (
  'active',
  'archived'
);

CREATE TYPE point_transaction_type AS ENUM (
  'task_completed',
  'manual_adjustment',
  'reward_redemption',
  'correction'
);

CREATE TYPE service_request_status AS ENUM (
  'pending_review',
  'approved',
  'declined',
  'converted_to_task',
  'cancelled'
);

CREATE TYPE service_request_type AS ENUM (
  'task',
  'purchase',
  'ride',
  'permission',
  'other'
);

CREATE TYPE task_help_request_status AS ENUM (
  'open',
  'acknowledged',
  'resolved',
  'cancelled'
);

CREATE TYPE task_help_reason AS ENUM (
  'not_sure_what_to_do',
  'need_more_time',
  'need_adult_help',
  'missing_something',
  'cant_reach',
  'not_feeling_well',
  'other'
);

-- ============================================================
-- TABLES
-- ============================================================

-- ------------------------------------------------------------
-- profiles
-- Application-level profile, 1:1 with auth.users.
-- Permissions come from household_members, not from this table.
-- ------------------------------------------------------------
CREATE TABLE profiles (
  id                   uuid        PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  display_name         text        NOT NULL,
  avatar_url           text        NULL,  -- optional; set later
  default_household_id uuid        NULL,  -- nullable: no household exists yet at signup; FK added after households table
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now()
);

-- ------------------------------------------------------------
-- households
-- Family workspace boundary. All domain data is scoped here.
-- ------------------------------------------------------------
CREATE TABLE households (
  id                    uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  name                  text        NOT NULL,
  created_by_profile_id uuid        NOT NULL REFERENCES profiles (id) ON DELETE RESTRICT,
  -- RESTRICT: household should survive if creator profile is deactivated; handle reassignment separately
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now()
);

-- Now that households exists, add FK for profiles.default_household_id
ALTER TABLE profiles
  ADD CONSTRAINT fk_profiles_default_household
  FOREIGN KEY (default_household_id)
  REFERENCES households (id)
  ON DELETE SET NULL;  -- if household is deleted, clear default preference; profile survives

CREATE INDEX idx_households_created_by ON households (created_by_profile_id);

-- ------------------------------------------------------------
-- household_members
-- Membership and role assignment. Controls all permissions.
-- ------------------------------------------------------------
CREATE TABLE household_members (
  id                    uuid                  PRIMARY KEY DEFAULT gen_random_uuid(),
  household_id          uuid                  NOT NULL REFERENCES households (id) ON DELETE CASCADE,
  -- CASCADE: membership is meaningless without the household
  profile_id            uuid                  NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
  -- CASCADE: remove membership if profile is deleted
  role                  household_member_role NOT NULL,
  display_name_override text                  NULL,  -- optional per-household display name (e.g. "Dad")
  joined_at             timestamptz           NOT NULL DEFAULT now(),
  created_at            timestamptz           NOT NULL DEFAULT now(),
  updated_at            timestamptz           NOT NULL DEFAULT now(),

  CONSTRAINT uq_household_members_household_profile UNIQUE (household_id, profile_id)
);

CREATE INDEX idx_household_members_household ON household_members (household_id);
CREATE INDEX idx_household_members_profile   ON household_members (profile_id);
CREATE INDEX idx_household_members_role      ON household_members (household_id, role);

-- ------------------------------------------------------------
-- tasks
-- Actual household commitments. A task exists only after an adult
-- creates or approves it. Pending service requests are not tasks.
-- MVP: nullable assignee_profile_id; no task_assignments table.
-- ------------------------------------------------------------
CREATE TABLE tasks (
  id                        uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  household_id              uuid        NOT NULL REFERENCES households (id) ON DELETE CASCADE,
  title                     text        NOT NULL,
  description               text        NULL,
  status                    task_status NOT NULL DEFAULT 'open',
  created_by_profile_id     uuid        NOT NULL REFERENCES profiles (id) ON DELETE RESTRICT,
  -- RESTRICT: preserve task history; don't silently delete tasks if creator is removed
  assigned_by_profile_id    uuid        NULL     REFERENCES profiles (id) ON DELETE SET NULL,
  -- SET NULL: if assigner's profile is removed, task survives; assigner field cleared
  assignee_profile_id       uuid        NULL     REFERENCES profiles (id) ON DELETE SET NULL,
  -- SET NULL: if assignee's profile is removed, task becomes unassigned; survives
  due_at                    timestamptz NULL,  -- nullable: not all tasks have deadlines
  points                    integer     NOT NULL DEFAULT 0,
  source_service_request_id uuid        NULL,
  -- FK to service_requests added after that table is created (circular dependency)
  completed_at              timestamptz NULL,  -- nullable: set when status = 'completed'
  completed_by_profile_id   uuid        NULL   REFERENCES profiles (id) ON DELETE SET NULL,
  created_at                timestamptz NOT NULL DEFAULT now(),
  updated_at                timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT chk_tasks_points_non_negative CHECK (points >= 0)
);

CREATE INDEX idx_tasks_household          ON tasks (household_id);
CREATE INDEX idx_tasks_assignee           ON tasks (assignee_profile_id);
CREATE INDEX idx_tasks_created_by         ON tasks (created_by_profile_id);
CREATE INDEX idx_tasks_status             ON tasks (status);
CREATE INDEX idx_tasks_due_at             ON tasks (due_at);
CREATE INDEX idx_tasks_household_status   ON tasks (household_id, status);
CREATE INDEX idx_tasks_household_assignee ON tasks (household_id, assignee_profile_id);

-- ------------------------------------------------------------
-- rewards
-- Household-scoped rewards redeemable with points.
-- ------------------------------------------------------------
CREATE TABLE rewards (
  id                    uuid          PRIMARY KEY DEFAULT gen_random_uuid(),
  household_id          uuid          NOT NULL REFERENCES households (id) ON DELETE CASCADE,
  title                 text          NOT NULL,
  description           text          NULL,
  points_required       integer       NOT NULL,
  status                reward_status NOT NULL DEFAULT 'active',
  created_by_profile_id uuid          NOT NULL REFERENCES profiles (id) ON DELETE RESTRICT,
  -- RESTRICT: preserve reward definition; don't silently remove if creator leaves
  created_at            timestamptz   NOT NULL DEFAULT now(),
  updated_at            timestamptz   NOT NULL DEFAULT now(),

  CONSTRAINT chk_rewards_points_positive CHECK (points_required > 0)
);

CREATE INDEX idx_rewards_household        ON rewards (household_id);
CREATE INDEX idx_rewards_status           ON rewards (status);
CREATE INDEX idx_rewards_household_status ON rewards (household_id, status);

-- ------------------------------------------------------------
-- points_balances
-- Current points balance per (household, profile).
-- MVP: no negative balances. No direct client UPDATE (see RLS strategy).
-- ------------------------------------------------------------
CREATE TABLE points_balances (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  household_id uuid        NOT NULL REFERENCES households (id) ON DELETE CASCADE,
  profile_id   uuid        NOT NULL REFERENCES profiles (id)  ON DELETE CASCADE,
  balance      integer     NOT NULL DEFAULT 0,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT uq_points_balances_household_profile UNIQUE (household_id, profile_id),
  CONSTRAINT chk_points_balance_non_negative      CHECK  (balance >= 0)
);

CREATE INDEX idx_points_balances_household ON points_balances (household_id);
CREATE INDEX idx_points_balances_profile   ON points_balances (profile_id);

-- ------------------------------------------------------------
-- point_transactions
-- Immutable audit trail for all point changes.
-- No updated_at: rows are never modified after insert.
-- ------------------------------------------------------------
CREATE TABLE point_transactions (
  id                    uuid                   PRIMARY KEY DEFAULT gen_random_uuid(),
  household_id          uuid                   NOT NULL REFERENCES households (id) ON DELETE CASCADE,
  profile_id            uuid                   NOT NULL REFERENCES profiles (id)   ON DELETE RESTRICT,
  -- RESTRICT: don't silently lose transaction history if a profile is removed
  type                  point_transaction_type NOT NULL,
  amount                integer                NOT NULL,  -- positive = earned, negative = spent
  balance_after         integer                NULL,      -- denormalized snapshot; aids audit/debugging
  task_id               uuid                   NULL REFERENCES tasks (id)   ON DELETE SET NULL,
  reward_id             uuid                   NULL REFERENCES rewards (id) ON DELETE SET NULL,
  created_by_profile_id uuid                   NULL REFERENCES profiles (id) ON DELETE SET NULL,
  note                  text                   NULL,  -- required at app layer for type = 'correction'
  created_at            timestamptz            NOT NULL DEFAULT now()
);

CREATE INDEX idx_point_txn_household         ON point_transactions (household_id);
CREATE INDEX idx_point_txn_profile           ON point_transactions (profile_id);
CREATE INDEX idx_point_txn_task              ON point_transactions (task_id);
CREATE INDEX idx_point_txn_reward            ON point_transactions (reward_id);
CREATE INDEX idx_point_txn_created_at        ON point_transactions (created_at);
CREATE INDEX idx_point_txn_household_profile ON point_transactions (household_id, profile_id, created_at);

-- ------------------------------------------------------------
-- service_requests
-- Requests that may become tasks. A pending request is NOT a task.
-- Only adult approval can convert a service_request to a task.
-- ------------------------------------------------------------
CREATE TABLE service_requests (
  id                       uuid                   PRIMARY KEY DEFAULT gen_random_uuid(),
  household_id             uuid                   NOT NULL REFERENCES households (id) ON DELETE CASCADE,
  request_type             service_request_type   NOT NULL DEFAULT 'task',
  status                   service_request_status NOT NULL DEFAULT 'pending_review',
  requested_by_profile_id  uuid                   NOT NULL REFERENCES profiles (id) ON DELETE RESTRICT,
  -- RESTRICT: preserve request history; don't silently remove requests
  requested_for_profile_id uuid                   NULL     REFERENCES profiles (id) ON DELETE SET NULL,
  reviewed_by_profile_id   uuid                   NULL     REFERENCES profiles (id) ON DELETE SET NULL,
  title                    text                   NOT NULL,
  description              text                   NULL,
  decline_reason           text                   NULL,  -- UI must use gentle copy; never show raw to children
  converted_task_id        uuid                   NULL,
  -- FK to tasks(id) added below after circular dependency is resolved
  reviewed_at              timestamptz            NULL,
  converted_at             timestamptz            NULL,
  created_at               timestamptz            NOT NULL DEFAULT now(),
  updated_at               timestamptz            NOT NULL DEFAULT now()
);

CREATE INDEX idx_srequests_household        ON service_requests (household_id);
CREATE INDEX idx_srequests_status           ON service_requests (status);
CREATE INDEX idx_srequests_type             ON service_requests (request_type);
CREATE INDEX idx_srequests_requested_by     ON service_requests (requested_by_profile_id);
CREATE INDEX idx_srequests_requested_for    ON service_requests (requested_for_profile_id);
CREATE INDEX idx_srequests_reviewed_by      ON service_requests (reviewed_by_profile_id);
CREATE INDEX idx_srequests_household_status ON service_requests (household_id, status);

-- ------------------------------------------------------------
-- Resolve circular FK: tasks ↔ service_requests
-- tasks.source_service_request_id → service_requests(id)
-- service_requests.converted_task_id → tasks(id)
-- Both are SET NULL on delete to avoid hard deletion cascades across the cycle.
-- ------------------------------------------------------------
ALTER TABLE tasks
  ADD CONSTRAINT fk_tasks_source_service_request
  FOREIGN KEY (source_service_request_id)
  REFERENCES service_requests (id)
  ON DELETE SET NULL;

ALTER TABLE service_requests
  ADD CONSTRAINT fk_service_requests_converted_task
  FOREIGN KEY (converted_task_id)
  REFERENCES tasks (id)
  ON DELETE SET NULL;

-- ------------------------------------------------------------
-- task_help_requests
-- Help requests for existing, already-assigned tasks.
-- A help request does NOT create a new task.
-- household_id is denormalized from tasks for RLS efficiency.
-- ------------------------------------------------------------
CREATE TABLE task_help_requests (
  id                         uuid                     PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id                    uuid                     NOT NULL REFERENCES tasks      (id) ON DELETE CASCADE,
  -- CASCADE: help request is meaningless without its parent task
  household_id               uuid                     NOT NULL REFERENCES households (id) ON DELETE CASCADE,
  requested_by_profile_id    uuid                     NOT NULL REFERENCES profiles   (id) ON DELETE RESTRICT,
  requested_to_profile_id    uuid                     NULL     REFERENCES profiles   (id) ON DELETE SET NULL,
  status                     task_help_request_status NOT NULL DEFAULT 'open',
  reason                     task_help_reason         NOT NULL,
  note                       text                     NULL,
  acknowledged_by_profile_id uuid                     NULL     REFERENCES profiles   (id) ON DELETE SET NULL,
  resolved_by_profile_id     uuid                     NULL     REFERENCES profiles   (id) ON DELETE SET NULL,
  acknowledged_at            timestamptz              NULL,
  resolved_at                timestamptz              NULL,
  cancelled_at               timestamptz              NULL,
  created_at                 timestamptz              NOT NULL DEFAULT now(),
  updated_at                 timestamptz              NOT NULL DEFAULT now()

  -- Future: partial unique index to allow only one open help request per task:
  -- CREATE UNIQUE INDEX uq_one_open_help_request_per_task
  --   ON task_help_requests (task_id) WHERE status = 'open';
  -- Deferred until MVP behavior is confirmed.
);

CREATE INDEX idx_threquests_task             ON task_help_requests (task_id);
CREATE INDEX idx_threquests_household        ON task_help_requests (household_id);
CREATE INDEX idx_threquests_status           ON task_help_requests (status);
CREATE INDEX idx_threquests_requested_by     ON task_help_requests (requested_by_profile_id);
CREATE INDEX idx_threquests_requested_to     ON task_help_requests (requested_to_profile_id);
CREATE INDEX idx_threquests_household_status ON task_help_requests (household_id, status);
CREATE INDEX idx_threquests_task_status      ON task_help_requests (task_id, status);

-- ============================================================
-- ENABLE ROW LEVEL SECURITY
-- All domain tables have RLS enabled.
-- No policies are created in this migration.
-- Policies will be added in T1.4.5.
-- ============================================================

ALTER TABLE profiles             ENABLE ROW LEVEL SECURITY;
ALTER TABLE households           ENABLE ROW LEVEL SECURITY;
ALTER TABLE household_members    ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks                ENABLE ROW LEVEL SECURITY;
ALTER TABLE rewards              ENABLE ROW LEVEL SECURITY;
ALTER TABLE points_balances      ENABLE ROW LEVEL SECURITY;
ALTER TABLE point_transactions   ENABLE ROW LEVEL SECURITY;
ALTER TABLE service_requests     ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_help_requests   ENABLE ROW LEVEL SECURITY;
