-- Storage bucket + policies for uploaded profile avatar photos.
--
-- IMPORTANT — testing limitation: unlike every other migration in this
-- repo, this one could NOT be validated against a real local Postgres
-- instance. storage.objects, storage.buckets, and storage.foldername()
-- are part of Supabase's platform-managed Storage extension, not
-- available in a vanilla Postgres instance the way auth.uid() could be
-- mocked for the app-schema RLS migrations. This migration is written to
-- documented Supabase Storage RLS conventions and is syntax-valid, but
-- has only been verified by direct application to a live Supabase
-- project, not by an independent authorization test matrix. Test the
-- upload flow live after applying this.
--
-- Path convention: avatars/{auth.uid()}/{filename} — storage.foldername()
-- splits an object path on '/' and returns the segments as an array;
-- index 1 is the first folder, i.e. the uploader's own uid.
--
-- Migration history rule: do not edit this file after it is applied.

INSERT INTO storage.buckets (id, name, public)
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO NOTHING;

-- Public bucket: reads go through the CDN-style public URL
-- (getPublicUrl()), which bypasses RLS entirely — no SELECT policy is
-- needed for read access. Only write operations are gated below.

CREATE POLICY avatars_insert_own_folder
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'avatars'
  AND (storage.foldername(name))[1] = auth.uid()::text
);

CREATE POLICY avatars_update_own_folder
ON storage.objects
FOR UPDATE
TO authenticated
USING (
  bucket_id = 'avatars'
  AND (storage.foldername(name))[1] = auth.uid()::text
)
WITH CHECK (
  bucket_id = 'avatars'
  AND (storage.foldername(name))[1] = auth.uid()::text
);

CREATE POLICY avatars_delete_own_folder
ON storage.objects
FOR DELETE
TO authenticated
USING (
  bucket_id = 'avatars'
  AND (storage.foldername(name))[1] = auth.uid()::text
);
