-- Fixes createHouseholdWithOwner's Step 2 (src/lib/repositories/households.ts)
-- failing on every household creation with:
--
--   ERROR: new row violates row-level security policy for table "household_members"
--
-- Same root cause as 20260709000000_fix_households_select_on_create.sql, now
-- hitting household_members' own self-insert. Step 2 does
-- `.insert({...}).select('*').single()` to register the creator as 'owner'.
-- Postgres must check that inserted row against household_members_select_member
-- (from 20260707000000_core_rls_policies.sql) to satisfy RETURNING:
--
--   USING ( internal.is_household_member(household_id, auth.uid()) )
--
-- internal.is_household_member looks up household_members for a matching row
-- — but from this INSERT statement's own snapshot, the row it is currently
-- inserting is not yet visible to that nested self-referential lookup, so the
-- check fails and Postgres rejects the RETURNING clause outright. Reproduced
-- against a real local Postgres instance (fresh household, first-ever
-- member, zero prior household_members rows) before writing this fix.
--
-- Fix: let the caller see a household_members row that is their own,
-- regardless of whether the membership-lookup helper can already see it.
-- Does not widen access beyond what the row already grants moments later
-- anyway (a member can always see their own membership).
--
-- Migration history rule: do not edit this file after it is applied.

DROP POLICY household_members_select_member ON household_members;

CREATE POLICY household_members_select_member
ON household_members
FOR SELECT
TO authenticated
USING (
  profile_id = auth.uid()
  OR internal.is_household_member(household_id, auth.uid())
);
