-- Task Completion Photo Proof — Slice 1: task_completion_submissions schema.
--
-- One row per completion attempt (not per task). tasks.status remains the
-- workflow authority — this table exists to represent what today's task
-- lifecycle cannot: attempt identity, optional photo evidence, and an
-- immutable historical outcome per attempt (see docs discussion — a
-- rejected attempt is retained, a retry creates a NEW row, not an update
-- of the old one).
--
-- This migration is schema-only: no RPCs, no Storage bucket, no client
-- mutation path of any kind. REVOKE ALL + a single SELECT-only RLS
-- policy leaves this table fully unwritable from any client role —
-- lifecycle mutation is added in a later migration via SECURITY DEFINER
-- RPCs, matching this codebase's established convention for every
-- reviewable entity (contribution_claims, reward_redemptions).
--
-- task_id FK — ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED, not
-- RESTRICT: household deletion cascades both tasks (via tasks.household_id
-- ON DELETE CASCADE, existing) and this table's own rows (via
-- household_id ON DELETE CASCADE, below) as two independent sibling
-- cascade actions off the same household row — Postgres does not
-- guarantee their relative order. A plain RESTRICT is checked
-- immediately and is never deferrable, so if the tasks cascade happened
-- to run first, it would find a still-existing submission row and abort
-- the whole household deletion. Deferring the check to end-of-transaction
-- (only NO ACTION can be made deferrable; RESTRICT cannot) means that by
-- commit time both sibling cascades have completed regardless of order,
-- so a household deletion always succeeds cleanly, while a standalone
-- task deletion (its own implicit one-statement transaction) still fails
-- at that same commit boundary if submission history remains and nothing
-- else in that transaction removed it — preserving "a task with
-- completion history cannot be silently deleted" without breaking whole-
-- household deletion.
--
-- reviewed_by_profile_id stays ON DELETE SET NULL (consistent with
-- reward_redemptions' own reviewer column), but — unlike
-- reward_redemptions' own chk_reward_redemptions_review_metadata_consistency,
-- which requires reviewed_by_profile_id IS NOT NULL in its terminal branch
-- and would make that SET NULL action raise a check_violation the moment
-- a reviewer's profile is ever deleted — the CHECK below deliberately
-- does NOT require reviewed_by_profile_id IS NOT NULL in the terminal
-- branch. The review RPC (Slice 2) still always sets it at the moment of
-- a real transition; the relaxed CHECK only avoids blocking a later,
-- unrelated profile-deletion lifecycle event. reward_redemptions' own
-- version of this same contradiction is a separate, pre-existing item,
-- not addressed by this migration.
--
-- uq_tcs_photo_storage_path: at most one submission row may ever
-- reference a given Storage object — a rejected attempt's immutable
-- evidence must not later be attached directly to a different attempt.
-- Standard SQL UNIQUE semantics treat every NULL as distinct, so this
-- does not limit how many photo-less submissions can exist. NOTE for
-- Slice 2: this introduces a third possible unique_violation cause in
-- request_task_completion_v2's INSERT (alongside the idempotency key and
-- the one-pending-per-task partial index) — reserve ERRCODE CH018
-- ("evidence object already attached to another submission") for it.
-- Not implemented here — this migration adds no RPC of any kind.
--
-- Migration history rule: do not edit this file after it is applied.

CREATE TYPE task_completion_submission_status AS ENUM (
  'pending',
  'approved',
  'rejected'
);

CREATE TABLE task_completion_submissions (
  id                      uuid                                NOT NULL DEFAULT gen_random_uuid(),
  task_id                 uuid                                NOT NULL REFERENCES tasks (id)
                            ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
  household_id            uuid                                NOT NULL REFERENCES households (id) ON DELETE CASCADE,
  submitted_by_profile_id uuid                                NOT NULL REFERENCES profiles (id) ON DELETE RESTRICT,
  client_request_id       uuid                                NOT NULL,
  photo_storage_path      text                                NULL,
  status                  task_completion_submission_status  NOT NULL DEFAULT 'pending',
  reviewed_by_profile_id  uuid                                NULL REFERENCES profiles (id) ON DELETE SET NULL,
  reviewed_at             timestamptz                         NULL,
  submitted_at            timestamptz                         NOT NULL DEFAULT now(),
  created_at              timestamptz                         NOT NULL DEFAULT now(),
  updated_at              timestamptz                         NOT NULL DEFAULT now(),

  CONSTRAINT pk_task_completion_submissions PRIMARY KEY (id),

  -- PENDING: no reviewer yet. TERMINAL: reviewed_at is always set at the
  -- moment of review; reviewed_by_profile_id may later become NULL as a
  -- consequence of profile deletion (ON DELETE SET NULL above) — see this
  -- file's own header comment for why the terminal branch does not also
  -- require reviewed_by_profile_id IS NOT NULL.
  CONSTRAINT chk_tcs_review_metadata_consistency CHECK (
    (status = 'pending' AND reviewed_by_profile_id IS NULL AND reviewed_at IS NULL)
    OR
    (status IN ('approved', 'rejected') AND reviewed_at IS NOT NULL)
  ),

  -- Idempotency: one logical submission attempt = one client_request_id,
  -- scoped per submitter (mirrors uq_reward_redemptions_idempotency_key).
  CONSTRAINT uq_tcs_idempotency_key UNIQUE (submitted_by_profile_id, client_request_id),

  -- At most one submission row may ever reference a given Storage object
  -- — see header comment. NULL (no photo) is unrestricted.
  CONSTRAINT uq_tcs_photo_storage_path UNIQUE (photo_storage_path)
);

CREATE INDEX idx_tcs_task              ON task_completion_submissions (task_id);
CREATE INDEX idx_tcs_household         ON task_completion_submissions (household_id);
CREATE INDEX idx_tcs_submitted_by      ON task_completion_submissions (submitted_by_profile_id);
CREATE INDEX idx_tcs_status            ON task_completion_submissions (status);
CREATE INDEX idx_tcs_household_status  ON task_completion_submissions (household_id, status);

-- At most one PENDING submission per task — partial, so it stops applying
-- the moment a submission leaves 'pending'. Mirrors
-- uq_reward_redemptions_one_pending_per_child_reward /
-- uq_contribution_claims_one_pending_per_member exactly.
CREATE UNIQUE INDEX uq_tcs_one_pending_per_task
  ON task_completion_submissions (task_id)
  WHERE status = 'pending';

ALTER TABLE task_completion_submissions ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- Privilege boundary: explicit least privilege, both layers required
-- ============================================================
--
-- No table-level privilege of any kind for PUBLIC or anon — not even
-- SELECT. This is stricter than reward_redemptions' own precedent, which
-- only revokes INSERT/UPDATE/DELETE and leaves anon's SELECT to be
-- filtered to zero rows by RLS alone. That works, but relies on a single
-- layer; this table closes the coarser table-privilege layer too, at no
-- cost, matching the same defense-in-depth conviction this codebase
-- already applied once it found a real anon-privilege gap on
-- household_invites. authenticated gets table-level SELECT only — RLS
-- (below) is what actually decides which rows a given authenticated
-- caller may see. INSERT/UPDATE/DELETE remain unreachable for every
-- client role, by construction — lifecycle mutation is RPC-only,
-- added in a later migration.
REVOKE ALL ON public.task_completion_submissions FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.task_completion_submissions TO authenticated;

-- Self access requires CURRENT household membership, not merely having
-- once been the submitter — a former member must lose access to their
-- own historical submission the moment they leave the household, even
-- though the row itself is retained. Reviewer access (owner/admin/adult)
-- is likewise based on current membership only.
CREATE POLICY task_completion_submissions_select_self_or_adult_plus
ON task_completion_submissions
FOR SELECT
TO authenticated
USING (
  (
    submitted_by_profile_id = auth.uid()
    AND internal.is_household_member(household_id, auth.uid())
  )
  OR internal.is_household_member(household_id, auth.uid(), ARRAY['owner','admin','adult']::household_member_role[])
);

-- No INSERT/UPDATE/DELETE policy of any kind — RLS default-deny handles
-- those, with the explicit REVOKE ALL above as an independent second
-- layer against the same client-write path, mirroring
-- reward_redemptions' own established two-layer convention.
