-- Awards points atomically on task completion. EX-10 — see
-- docs/task-state-contract.md §10.
--
-- Scope: task-completion points only (the two paths that reach
-- status = 'completed': complete_task's direct completion and
-- approve_task_completion's review approval). Contribution-claim points
-- remain explicitly out of scope — approveContributionClaim.ts's own
-- "points deferred" comment is untouched by this migration.
--
-- Points source: tasks.points (integer NOT NULL DEFAULT 0, CHECK >= 0,
-- initial_schema.sql). No multiplier, bonus, or role-based calculation —
-- the awarded amount is exactly the task's own points value, unchanged
-- since creation.
--
-- Atomicity + exactly-once: both functions already guard their UPDATE
-- with a compare-and-swap WHERE clause (status = 'open' /
-- 'needs_attention') and RAISE EXCEPTION when it matches zero rows —
-- that exception aborts the entire function (and the caller's
-- transaction) before any code after it runs. The points-award block
-- below is placed strictly after that guard, inside the same function
-- body, with no internal BEGIN/COMMIT — so a retry, duplicate
-- invocation, or already-completed task never reaches the points-award
-- statements at all. No separate idempotency key or client-side
-- duplicate-prevention is introduced; the existing transition guard is
-- the sole enforcement mechanism, reused rather than duplicated.
--
-- Ledger shape: points_balances is upserted (ON CONFLICT on its existing
-- uq_points_balances_household_profile constraint) since no balance row
-- is auto-created when a member joins a household. point_transactions
-- records type = 'task_completed' (existing enum value, no new type
-- added), amount = the awarded points, balance_after = the post-upsert
-- balance (read back via RETURNING, not recomputed separately, so it
-- can never disagree with the balance actually stored).
--
-- completed_by_profile_id is already the correct recipient in both
-- functions (v_caller for direct completion, the task's own assignee
-- for approval — the existing worker-credit rule from
-- docs/task-state-contract.md §11) — points are credited to that same
-- profile, not the caller.
--
-- A task with points = 0 still produces a balance upsert (+0, a no-op
-- on the stored value) and a point_transactions row. This keeps every
-- completion producing one ledger entry unconditionally rather than
-- special-casing zero — not a new calculation rule, just avoiding an
-- amount-based branch the schema doesn't itself define.
--
-- Migration history rule: do not edit this file after it is applied.

CREATE OR REPLACE FUNCTION public.complete_task(p_task_id uuid)
RETURNS tasks
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_caller      uuid := auth.uid();
  v_task        tasks%ROWTYPE;
  v_new_balance integer;
BEGIN
  IF v_caller IS NULL THEN
    RAISE EXCEPTION 'Not authenticated' USING ERRCODE = '28000';
  END IF;

  SELECT * INTO v_task FROM tasks WHERE id = p_task_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Task not found' USING ERRCODE = 'P0002';
  END IF;

  IF NOT internal.is_household_member(
    v_task.household_id, v_caller, ARRAY['owner','admin','adult']::household_member_role[]
  ) THEN
    RAISE EXCEPTION 'Not authorized to complete this task' USING ERRCODE = '28000';
  END IF;

  UPDATE tasks
  SET status                  = 'completed',
      completed_at            = now(),
      completed_by_profile_id = v_caller
  WHERE id = p_task_id
    AND status = 'open'
  RETURNING * INTO v_task;

  IF NOT FOUND THEN
    -- Task existed and caller was authorized, but status was not 'open' at
    -- the moment of the UPDATE (already completed, or otherwise moved) —
    -- either genuinely stale, or lost a race between the SELECT above and
    -- this UPDATE. Both are "not open" from the caller's point of view.
    -- Aborts here — nothing below this point ever runs for a retry or an
    -- already-completed task.
    RAISE EXCEPTION 'Task is not open' USING ERRCODE = 'CH002';
  END IF;

  INSERT INTO points_balances (household_id, profile_id, balance)
  VALUES (v_task.household_id, v_task.completed_by_profile_id, v_task.points)
  ON CONFLICT ON CONSTRAINT uq_points_balances_household_profile
  DO UPDATE SET balance = points_balances.balance + EXCLUDED.balance,
                updated_at = now()
  RETURNING balance INTO v_new_balance;

  INSERT INTO point_transactions
    (household_id, profile_id, type, amount, balance_after, task_id, created_by_profile_id)
  VALUES
    (v_task.household_id, v_task.completed_by_profile_id, 'task_completed',
     v_task.points, v_new_balance, v_task.id, v_caller);

  RETURN v_task;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.complete_task(uuid) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION public.complete_task(uuid) TO authenticated;

CREATE OR REPLACE FUNCTION public.approve_task_completion(p_task_id uuid)
RETURNS tasks
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_caller      uuid := auth.uid();
  v_task        tasks%ROWTYPE;
  v_new_balance integer;
BEGIN
  IF v_caller IS NULL THEN
    RAISE EXCEPTION 'Not authenticated' USING ERRCODE = '28000';
  END IF;

  SELECT * INTO v_task FROM tasks WHERE id = p_task_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Task not found' USING ERRCODE = 'P0002';
  END IF;

  IF NOT internal.is_household_member(
    v_task.household_id, v_caller, ARRAY['owner','admin','adult']::household_member_role[]
  ) THEN
    RAISE EXCEPTION 'Not authorized to approve this task' USING ERRCODE = '28000';
  END IF;

  UPDATE tasks
  SET status                  = 'completed',
      completed_at            = now(),
      completed_by_profile_id = v_task.assignee_profile_id
  WHERE id = p_task_id
    AND status = 'needs_attention'
  RETURNING * INTO v_task;

  IF NOT FOUND THEN
    -- Task existed and caller was authorized, but status was not
    -- 'needs_attention' at the moment of the UPDATE (already reviewed,
    -- or otherwise moved) — either genuinely stale, or lost a race
    -- between the SELECT above and this UPDATE. Both are "not pending
    -- review" from the caller's point of view. Aborts here — nothing
    -- below this point ever runs for a retry or an already-reviewed task.
    RAISE EXCEPTION 'Task is not pending review' USING ERRCODE = 'CH004';
  END IF;

  INSERT INTO points_balances (household_id, profile_id, balance)
  VALUES (v_task.household_id, v_task.completed_by_profile_id, v_task.points)
  ON CONFLICT ON CONSTRAINT uq_points_balances_household_profile
  DO UPDATE SET balance = points_balances.balance + EXCLUDED.balance,
                updated_at = now()
  RETURNING balance INTO v_new_balance;

  INSERT INTO point_transactions
    (household_id, profile_id, type, amount, balance_after, task_id, created_by_profile_id)
  VALUES
    (v_task.household_id, v_task.completed_by_profile_id, 'task_completed',
     v_task.points, v_new_balance, v_task.id, v_caller);

  RETURN v_task;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.approve_task_completion(uuid) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION public.approve_task_completion(uuid) TO authenticated;
