-- Rewards Redemption — anon EXECUTE privilege closure.
--
-- Live QA verification (ChoreHero QA, post-deploy of
-- 20260822010000_reward_redemption_rpcs.sql) found that although PUBLIC
-- EXECUTE was correctly revoked and authenticated EXECUTE correctly
-- granted, anon still held direct EXECUTE on all three RPCs:
--
--   PUBLIC        -> false  (correct)
--   authenticated -> true   (correct)
--   anon          -> true   (gap)
--
-- Root cause: REVOKE ... FROM PUBLIC only removes the privilege a role
-- receives *through* the PUBLIC pseudo-role. Supabase provisions every
-- project with a database-level default
-- (ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO
-- anon, authenticated, service_role) that grants EXECUTE to anon
-- *directly* the moment each function is created — a separate grant path
-- REVOKE ... FROM PUBLIC never touches. Each RPC's own internal
-- auth.uid() IS NULL guard still rejects an actual anon (unauthenticated)
-- call at the application-logic layer, but the privilege-layer defense
-- this design relies on (the same "REVOKE + RLS, both required" pattern
-- used for reward_redemptions itself) was down to one layer instead of
-- two for anon specifically.
--
-- This migration closes that gap. Additive only: no RPC body, parameter,
-- return type, SECURITY DEFINER, search_path, auth.uid() handling,
-- household-role authorization, error code, schema, or RLS change of any
-- kind. Does not touch ALTER DEFAULT PRIVILEGES (that would affect
-- unrelated/future functions, out of this feature's scope) — only
-- revokes the already-granted privilege on these three specific,
-- already-existing functions.
--
-- Migration history rule: do not edit this file after it is applied.

REVOKE EXECUTE ON FUNCTION public.request_reward_redemption(uuid, uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.approve_reward_redemption(uuid)       FROM anon;
REVOKE EXECUTE ON FUNCTION public.reject_reward_redemption(uuid)        FROM anon;
