-- Parent approval/rejection of a child completion request. EX-07 — see
-- docs/task-state-contract.md §§9,11.
--
-- Mirrors claim_open_task's, complete_task's, and request_task_completion's
-- approved architecture (Option B — SECURITY DEFINER RPC), per the same
-- ADR-002 reasoning: RLS's WITH CHECK cannot assert "only status (and, on
-- approval, completed_at/completed_by_profile_id) changed" without
-- column-diffing. These RPCs' own bodies are the entire enforcement surface
-- for these two specific transitions, exactly as the three prior RPCs
-- already are for theirs. RLS (tasks_update_adult_plus_or_assignee) is
-- untouched and remains defense-in-depth only, per the merged contract's
-- §11 statement — it is not the authoritative mutation boundary for this
-- transition.
--
--   - Both functions live in `public`, matching every existing
--     client-callable RPC in this codebase.
--   - Column-scoping is structural: only p_task_id is accepted by each
--     function, and each SET clause only ever touches the columns named
--     below — assignee_profile_id and points are untouched by
--     construction, not by policy.
--   - Approved product decision ("completed_by_profile_id represents
--     worker credit"): approve_task_completion sets
--     completed_by_profile_id to the task's own assignee_profile_id
--     (read in the initial SELECT), never to the caller (v_caller). This
--     is the one place these two RPCs' SET clauses differ in kind from
--     complete_task's `= v_caller` pattern — the approving adult is never
--     recorded as the completion owner. No separate
--     approved_by_profile_id field is introduced (contract §11).
--   - Authorization is role-based (owner/admin/adult), matching
--     complete_task's exact role list — this is the same privileged tier
--     that performs direct completion (EX-05) also performing review
--     (EX-07).
--   - The compare-and-swap WHERE status = 'needs_attention' makes each
--     function idempotent in the safe sense: a second approve/reject
--     attempt on an already-reviewed row, or one racing the other
--     reviewer action, raises a dedicated code rather than silently
--     succeeding or double-writing. Neither cause is distinguished from
--     the other, matching the same collapse-into-one-outcome convention
--     complete_task (CH002) and request_task_completion (CH003) already
--     establish for themselves.
--   - CH004 (approve) / CH005 (reject) are new, project-specific codes,
--     extending the existing sequential CH001/CH002/CH003 allocation.
--   - Does not touch, replace, or narrow tasks_update_adult_plus_or_assignee.
--     Does not touch claim_open_task, complete_task, or
--     request_task_completion.
--
-- Out of scope, deliberately: points award, rewards, notifications,
-- history/review records, in_progress, new task states, a separate
-- reviewer-identity field. See docs/task-state-contract.md for the full
-- contract these implement against.
--
-- Migration history rule: do not edit this file after it is applied.

CREATE OR REPLACE FUNCTION public.approve_task_completion(p_task_id uuid)
RETURNS tasks
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_caller uuid := auth.uid();
  v_task   tasks%ROWTYPE;
BEGIN
  IF v_caller IS NULL THEN
    RAISE EXCEPTION 'Not authenticated' USING ERRCODE = '28000';
  END IF;

  SELECT * INTO v_task FROM tasks WHERE id = p_task_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Task not found' USING ERRCODE = 'P0002';
  END IF;

  IF NOT internal.is_household_member(
    v_task.household_id, v_caller, ARRAY['owner','admin','adult']::household_member_role[]
  ) THEN
    RAISE EXCEPTION 'Not authorized to approve this task' USING ERRCODE = '28000';
  END IF;

  UPDATE tasks
  SET status                  = 'completed',
      completed_at            = now(),
      completed_by_profile_id = v_task.assignee_profile_id
  WHERE id = p_task_id
    AND status = 'needs_attention'
  RETURNING * INTO v_task;

  IF NOT FOUND THEN
    -- Task existed and caller was authorized, but status was not
    -- 'needs_attention' at the moment of the UPDATE (already reviewed,
    -- or otherwise moved) — either genuinely stale, or lost a race
    -- between the SELECT above and this UPDATE. Both are "not pending
    -- review" from the caller's point of view.
    RAISE EXCEPTION 'Task is not pending review' USING ERRCODE = 'CH004';
  END IF;

  RETURN v_task;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.approve_task_completion(uuid) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION public.approve_task_completion(uuid) TO authenticated;

CREATE OR REPLACE FUNCTION public.reject_task_completion(p_task_id uuid)
RETURNS tasks
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_caller uuid := auth.uid();
  v_task   tasks%ROWTYPE;
BEGIN
  IF v_caller IS NULL THEN
    RAISE EXCEPTION 'Not authenticated' USING ERRCODE = '28000';
  END IF;

  SELECT * INTO v_task FROM tasks WHERE id = p_task_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Task not found' USING ERRCODE = 'P0002';
  END IF;

  IF NOT internal.is_household_member(
    v_task.household_id, v_caller, ARRAY['owner','admin','adult']::household_member_role[]
  ) THEN
    RAISE EXCEPTION 'Not authorized to reject this task' USING ERRCODE = '28000';
  END IF;

  UPDATE tasks
  SET status = 'open'
  WHERE id = p_task_id
    AND status = 'needs_attention'
  RETURNING * INTO v_task;

  IF NOT FOUND THEN
    -- Same "not pending review" condition as approve_task_completion,
    -- from the reject side.
    RAISE EXCEPTION 'Task is not pending review' USING ERRCODE = 'CH005';
  END IF;

  RETURN v_task;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.reject_task_completion(uuid) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION public.reject_task_completion(uuid) TO authenticated;
