-- Child completion request. EX-06 — see docs/task-state-contract.md §8.
--
-- Mirrors claim_open_task's and complete_task's approved architecture
-- (Option B — SECURITY DEFINER RPC) rather than a new RLS UPDATE policy,
-- for the same reason ADR-002 already gives: RLS's WITH CHECK cannot
-- assert "only status may move from open to needs_attention" without
-- column-diffing, which plain WITH CHECK cannot express. This RPC's own
-- body is the entire enforcement surface for this specific transition,
-- exactly as claim_open_task and complete_task already are for their own.
--
--   - Lives in `public`, matching claim_open_task, complete_task, and
--     redeem_household_invite — the existing precedent for
--     client-callable RPCs in this codebase.
--   - Column-scoping is structural: only p_task_id is accepted, and the
--     UPDATE's SET clause only ever touches status — completed_at,
--     completed_by_profile_id, assignee_profile_id, and points are
--     untouched by construction, not by policy, matching the task-state
--     contract's explicit requirement that EX-06 submission never sets
--     completion metadata.
--   - Assignment-authorization policy (approved product decision,
--     "Option A — assigned child only"): the caller must both (a) hold
--     the `child` role in the task's household, and (b) be the specific
--     profile referenced by tasks.assignee_profile_id on this task. A
--     different child in the same household — even one with an open,
--     unassigned task available to claim — is not authorized to submit
--     a completion request for a task assigned to someone else. Household
--     membership is not checked as an independent condition: because
--     assignee_profile_id can only ever hold a household member's id
--     (assignment happens only via insertTask or claim_open_task, both of
--     which already require household membership), condition (b) alone
--     structurally implies membership. internal.is_household_member is
--     still called explicitly below, purely to obtain a role-filtered
--     boolean in one call, matching the shape of every other RPC's
--     authorization check in this codebase — not because it adds
--     authorization power beyond the assignee check.
--   - Both authorization failure modes (wrong role, wrong assignee) are
--     collapsed into a single generic ERRCODE 28000, exactly matching
--     how claim_open_task and complete_task already collapse their own
--     distinct internal authorization-failure causes into one
--     externally-visible outcome.
--   - The compare-and-swap WHERE status = 'open' AND assignee_profile_id
--     = v_caller makes this idempotent in the safe sense: a second call
--     against an already-needs_attention (or otherwise non-open, or
--     no-longer-assigned-to-this-caller) task raises CH003 rather than
--     silently succeeding or silently double-writing. Including
--     assignee_profile_id in this same WHERE clause (not just the
--     earlier authorization check) closes the same TOCTOU race window
--     complete_task's own comment describes between its SELECT and its
--     UPDATE.
--   - CH003 is a new, project-specific code, extending the existing
--     sequential CH001 (claim_open_task) / CH002 (complete_task)
--     pattern. Like CH002, it does not distinguish "genuinely wrong
--     state" from "lost a race" — both collapse into one meaning, one
--     code, matching this project's established convention.
--   - Does not touch, replace, or narrow tasks_update_adult_plus_or_assignee.
--     Does not touch claim_open_task or complete_task.
--
-- Out of scope, deliberately: approval, rejection, points award,
-- in_progress, any review/history table. See docs/task-state-contract.md
-- §§6-11 for the full contract this implements against.
--
-- Migration history rule: do not edit this file after it is applied.

CREATE OR REPLACE FUNCTION public.request_task_completion(p_task_id uuid)
RETURNS tasks
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_caller uuid := auth.uid();
  v_task   tasks%ROWTYPE;
BEGIN
  IF v_caller IS NULL THEN
    RAISE EXCEPTION 'Not authenticated' USING ERRCODE = '28000';
  END IF;

  SELECT * INTO v_task FROM tasks WHERE id = p_task_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Task not found' USING ERRCODE = 'P0002';
  END IF;

  IF NOT internal.is_household_member(
    v_task.household_id, v_caller, ARRAY['child']::household_member_role[]
  ) OR v_task.assignee_profile_id IS DISTINCT FROM v_caller THEN
    RAISE EXCEPTION 'Not authorized to request completion of this task' USING ERRCODE = '28000';
  END IF;

  UPDATE tasks
  SET status = 'needs_attention'
  WHERE id = p_task_id
    AND status = 'open'
    AND assignee_profile_id = v_caller
  RETURNING * INTO v_task;

  IF NOT FOUND THEN
    -- Task existed and caller was authorized, but status was not 'open'
    -- (already needs_attention/completed, or otherwise moved), or the
    -- assignment changed between the SELECT above and this UPDATE.
    -- Both are "not open" from the caller's point of view.
    RAISE EXCEPTION 'Task is not open' USING ERRCODE = 'CH003';
  END IF;

  RETURN v_task;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.request_task_completion(uuid) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION public.request_task_completion(uuid) TO authenticated;
