-- Adult/admin/owner direct task completion. EX-05 — see docs/task-state-contract.md.
--
-- Mirrors claim_open_task's approved architecture (Option B — SECURITY
-- DEFINER RPC) rather than relying on the existing broad
-- tasks_update_adult_plus_or_assignee UPDATE policy. That policy already
-- permits an assignee (including a child) to update any column on their
-- own assigned task — RLS alone cannot restrict "only status may move from
-- open to completed" without column-diffing, which plain WITH CHECK cannot
-- express. This RPC's own body is the entire enforcement surface for this
-- specific transition, exactly as claim_open_task already is for claiming.
--
--   - Lives in `public`, matching claim_open_task and
--     redeem_household_invite — the existing precedent for client-callable
--     RPCs in this codebase.
--   - Column-scoping is structural: only p_task_id is accepted, and the
--     UPDATE's SET clause only ever touches status, completed_at, and
--     completed_by_profile_id — assignee_profile_id and points are
--     untouched by construction, not by policy.
--   - completed_by_profile_id is set to auth.uid() directly. profiles.id
--     is a primary key that is a foreign key onto auth.users(id)
--     (20260624000000_initial_schema.sql:85-92), so profiles.id and
--     auth.uid() are identical by schema construction — no separate
--     profiles lookup is needed, matching how claim_open_task already
--     uses auth.uid() directly for assignee_profile_id.
--   - The compare-and-swap WHERE status = 'open' makes this idempotent in
--     the safe sense: a second call against an already-completed (or
--     otherwise non-open) task raises CH002 rather than silently
--     succeeding or silently double-writing completion metadata.
--   - Does not touch, replace, or narrow tasks_update_adult_plus_or_assignee.
--     Does not touch claim_open_task.
--
-- Out of scope, deliberately: child completion requests, needs_attention,
-- approval/rejection, points award, in_progress. See
-- docs/task-state-contract.md for the full contract this implements
-- against.
--
-- Migration history rule: do not edit this file after it is applied.

CREATE OR REPLACE FUNCTION public.complete_task(p_task_id uuid)
RETURNS tasks
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_caller uuid := auth.uid();
  v_task   tasks%ROWTYPE;
BEGIN
  IF v_caller IS NULL THEN
    RAISE EXCEPTION 'Not authenticated' USING ERRCODE = '28000';
  END IF;

  SELECT * INTO v_task FROM tasks WHERE id = p_task_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Task not found' USING ERRCODE = 'P0002';
  END IF;

  IF NOT internal.is_household_member(
    v_task.household_id, v_caller, ARRAY['owner','admin','adult']::household_member_role[]
  ) THEN
    RAISE EXCEPTION 'Not authorized to complete this task' USING ERRCODE = '28000';
  END IF;

  UPDATE tasks
  SET status                  = 'completed',
      completed_at            = now(),
      completed_by_profile_id = v_caller
  WHERE id = p_task_id
    AND status = 'open'
  RETURNING * INTO v_task;

  IF NOT FOUND THEN
    -- Task existed and caller was authorized, but status was not 'open' at
    -- the moment of the UPDATE (already completed, or otherwise moved) —
    -- either genuinely stale, or lost a race between the SELECT above and
    -- this UPDATE. Both are "not open" from the caller's point of view.
    RAISE EXCEPTION 'Task is not open' USING ERRCODE = 'CH002';
  END IF;

  RETURN v_task;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.complete_task(uuid) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION public.complete_task(uuid) TO authenticated;