-- T1.4.5 (deferred): core RLS policies for profiles, households,
-- household_members, tasks, rewards, points_balances, point_transactions.
--
-- These tables have had RLS enabled since 20260624000000_initial_schema.sql
-- but zero policies — confirmed both by grepping every migration (no
-- CREATE POLICY statements for any of them) and, since this migration was
-- written, by direct runtime evidence: a real profile-creation attempt
-- against production returned 403 Forbidden on an INSERT into profiles.
--
-- Scope is intentionally limited to what shipped client code actually
-- exercises today (see docs/rls-strategy.md for the full target matrix —
-- this migration does not implement every cell of it). Deliberately
-- deferred, matching the "don't add unused scaffolding" precedent already
-- set in 20260704000000_contribution_claims_rls.sql:
--   - household_members: no UPDATE/DELETE policy (no role-change or
--     leave-household feature is shipped yet)
--   - households: no UPDATE/DELETE policy (no edit/delete-household
--     feature is shipped yet)
--   - points_balances / point_transactions: read-only policies. No
--     INSERT/UPDATE/DELETE policy — matches docs/rls-strategy.md's
--     explicit "no direct client mutation" rule; all balance changes are
--     meant to go through a controlled RPC workflow that does not exist
--     yet, at which point it can run as SECURITY DEFINER or under the
--     service role, bypassing these (deliberately absent) write policies.
--
-- Migration history rule: do not edit this file after it is applied.

-- ============================================================
-- Cross-household-membership helper (SECURITY DEFINER)
-- ============================================================
--
-- internal.is_household_member (from 20260704000000) answers "is profile P
-- a member of household H". It cannot answer "do the caller and profile P
-- share ANY household", which profiles' SELECT policy below needs — so a
-- second, narrowly-scoped helper is added here, following the same
-- SECURITY DEFINER + internal-schema + REVOKE-FROM-PUBLIC pattern for the
-- same reason: an ordinary (non-SECURITY DEFINER) query from a profiles
-- policy against household_members would be subject to household_members'
-- own RLS, and evaluating that RLS for a policy that itself may reference
-- profiles could recurse. SECURITY DEFINER's internal query bypasses
-- household_members' RLS entirely, avoiding the cycle — the same
-- reasoning already documented for is_household_member itself.
CREATE OR REPLACE FUNCTION internal.shares_household_with(p_other_profile_id uuid)
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
STABLE
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM household_members hm_self
    JOIN household_members hm_other
      ON hm_other.household_id = hm_self.household_id
    WHERE hm_self.profile_id  = auth.uid()
      AND hm_other.profile_id = p_other_profile_id
  );
$$;

REVOKE EXECUTE ON FUNCTION internal.shares_household_with(uuid) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION internal.shares_household_with(uuid) TO authenticated;

-- ============================================================
-- profiles
-- ============================================================

-- SELECT: own profile always; other profiles only if sharing a household.
CREATE POLICY profiles_select_self_or_household_member
ON profiles
FOR SELECT
TO authenticated
USING (
  id = auth.uid()
  OR internal.shares_household_with(id)
);

-- INSERT: self only. docs/rls-strategy.md originally anticipated profile
-- creation happening via an auth trigger ("Create profile: no — created at
-- signup"); the shipped implementation (ensureProfileExists, called from
-- ProfileSetupScreen) instead does a client-side upsert, so the policy
-- matches what the code actually does rather than the original plan.
CREATE POLICY profiles_insert_self
ON profiles
FOR INSERT
TO authenticated
WITH CHECK (id = auth.uid());

-- UPDATE: self only for MVP. "Update other profiles: limited (admin) / yes
-- (owner)" from docs/rls-strategy.md is not implemented here — no shipped
-- feature edits another member's profile yet.
CREATE POLICY profiles_update_self
ON profiles
FOR UPDATE
TO authenticated
USING (id = auth.uid())
WITH CHECK (id = auth.uid());

-- No DELETE policy — matches "open question" in docs/rls-strategy.md;
-- default-deny until a decision is made.

-- ============================================================
-- households
-- ============================================================

-- SELECT: any member of the household.
CREATE POLICY households_select_member
ON households
FOR SELECT
TO authenticated
USING (
  internal.is_household_member(id, auth.uid())
);

-- INSERT: self-attributed only. No role check is possible here — the
-- household (and therefore any household_members row) does not exist yet
-- at the moment of creation. Matches createHouseholdWithOwner, the only
-- shipped code path that inserts into households.
CREATE POLICY households_insert_self_creator
ON households
FOR INSERT
TO authenticated
WITH CHECK (created_by_profile_id = auth.uid());

-- No UPDATE/DELETE policy — no edit/delete-household feature is shipped yet.

-- ============================================================
-- household_members
-- ============================================================

-- SELECT: any member of the same household can see the member list.
CREATE POLICY household_members_select_member
ON household_members
FOR SELECT
TO authenticated
USING (
  internal.is_household_member(household_id, auth.uid())
);

-- INSERT: self only. Covers both shipped paths — createHouseholdWithOwner
-- (self as 'owner', immediately after creating the household) and
-- joinHouseholdById (self as 'adult', using the household id as a join
-- code — see households.ts's own comments on that MVP behavior). No
-- "admin/owner adds a specific other member" feature is shipped yet, so no
-- policy branch is written for it.
CREATE POLICY household_members_insert_self
ON household_members
FOR INSERT
TO authenticated
WITH CHECK (profile_id = auth.uid());

-- No UPDATE/DELETE policy — no role-change or leave-household feature is
-- shipped yet.

-- ============================================================
-- tasks
-- ============================================================

CREATE POLICY tasks_select_household_member
ON tasks
FOR SELECT
TO authenticated
USING (
  internal.is_household_member(household_id, auth.uid())
);

CREATE POLICY tasks_insert_adult_plus
ON tasks
FOR INSERT
TO authenticated
WITH CHECK (
  created_by_profile_id = auth.uid()
  AND internal.is_household_member(household_id, auth.uid(), ARRAY['owner','admin','adult']::household_member_role[])
);

-- UPDATE: adult+ can update any field; the assignee (including a child) can
-- update their own assigned task. Row-level only — docs/rls-strategy.md is
-- explicit that field-level restriction (e.g. a child cannot reassign
-- their own task) is an application/RPC-layer concern, not RLS's.
CREATE POLICY tasks_update_adult_plus_or_assignee
ON tasks
FOR UPDATE
TO authenticated
USING (
  internal.is_household_member(household_id, auth.uid(), ARRAY['owner','admin','adult']::household_member_role[])
  OR assignee_profile_id = auth.uid()
)
WITH CHECK (
  internal.is_household_member(household_id, auth.uid(), ARRAY['owner','admin','adult']::household_member_role[])
  OR assignee_profile_id = auth.uid()
);

CREATE POLICY tasks_delete_admin_plus
ON tasks
FOR DELETE
TO authenticated
USING (
  internal.is_household_member(household_id, auth.uid(), ARRAY['owner','admin']::household_member_role[])
);

-- ============================================================
-- rewards
-- ============================================================

-- SELECT: active rewards visible to any household member; archived
-- rewards visible only to adult+.
CREATE POLICY rewards_select_household_scoped
ON rewards
FOR SELECT
TO authenticated
USING (
  internal.is_household_member(household_id, auth.uid())
  AND (
    status = 'active'
    OR internal.is_household_member(household_id, auth.uid(), ARRAY['owner','admin','adult']::household_member_role[])
  )
);

CREATE POLICY rewards_insert_adult_plus
ON rewards
FOR INSERT
TO authenticated
WITH CHECK (
  created_by_profile_id = auth.uid()
  AND internal.is_household_member(household_id, auth.uid(), ARRAY['owner','admin','adult']::household_member_role[])
);

CREATE POLICY rewards_update_adult_plus
ON rewards
FOR UPDATE
TO authenticated
USING (
  internal.is_household_member(household_id, auth.uid(), ARRAY['owner','admin','adult']::household_member_role[])
)
WITH CHECK (
  internal.is_household_member(household_id, auth.uid(), ARRAY['owner','admin','adult']::household_member_role[])
);

CREATE POLICY rewards_delete_admin_plus
ON rewards
FOR DELETE
TO authenticated
USING (
  internal.is_household_member(household_id, auth.uid(), ARRAY['owner','admin']::household_member_role[])
);

-- ============================================================
-- points_balances (read-only — see header note)
-- ============================================================

CREATE POLICY points_balances_select_self_or_adult_plus
ON points_balances
FOR SELECT
TO authenticated
USING (
  profile_id = auth.uid()
  OR internal.is_household_member(household_id, auth.uid(), ARRAY['owner','admin','adult']::household_member_role[])
);

-- ============================================================
-- point_transactions (read-only — see header note)
-- ============================================================

CREATE POLICY point_transactions_select_self_or_adult_plus
ON point_transactions
FOR SELECT
TO authenticated
USING (
  profile_id = auth.uid()
  OR internal.is_household_member(household_id, auth.uid(), ARRAY['owner','admin','adult']::household_member_role[])
);
