-- T1.7.3 Hardening Pass 1: contribution_claims RLS policies + duplicate-pending guard
--
-- Scope: RLS policies for contribution_claims only, plus the partial unique
-- index enforcing "at most one pending claim per (household, claimant)".
-- Does not touch tasks/rewards/points_balances/household_members RLS —
-- those remain out of scope (see note below).
--
-- Migration history rule: do not edit this file after it is applied.

-- ============================================================
-- Membership helper (SECURITY DEFINER)
-- ============================================================
--
-- household_members has RLS enabled (20260624000000_initial_schema.sql)
-- but no policies of its own yet — that is separate, pre-existing scope
-- (tracked as T1.4.5 in docs/roadmap.md, not part of this hardening pass).
-- Because of that, an ordinary (non-SECURITY DEFINER) subquery against
-- household_members from another table's policy would always see zero
-- rows for any authenticated caller, making every policy below vacuously
-- deny everything regardless of real membership.
--
-- This function exists solely to support RLS policy evaluation below —
-- it is not intended to be exposed as a public RPC interface. It runs as
-- its owner (bypassing household_members' RLS internally) and is the
-- only way these policies can correctly answer "is this profile an
-- active member of this household, with one of the given roles?".
--
-- Risk this addresses: the function takes profile_id as a caller-supplied
-- argument rather than always using auth.uid() internally. If it lived in
-- `public` with EXECUTE granted to `authenticated` (required for RLS to
-- invoke it), it would also be directly callable by any logged-in client
-- with arbitrary (household_id, profile_id) arguments — a cross-household
-- membership oracle, even though household_members itself has no SELECT
-- policy of its own.
--
-- Mitigation implemented and verified locally: the function is defined in
-- `internal`, a dedicated non-public helper schema, rather than `public`.
-- EXECUTE is revoked from PUBLIC and granted only to `authenticated` (the
-- minimum role required for the RLS policies below to invoke it). Local
-- PostgreSQL validation confirmed that direct invocation by the
-- `authenticated` role is rejected ("permission denied for schema
-- internal"), even when fully schema-qualified, while the RLS policies
-- below continue to invoke it correctly and produce the same
-- authorization results as before this change (the policy body resolves
-- the function reference once at CREATE POLICY time, so re-checking
-- schema USAGE at each row evaluation is not required for that path).
-- This project's live Supabase/PostgREST configuration was not available
-- to verify, so no claim is made here about whether `internal` is
-- additionally excluded from PostgREST's own schema routing.
--
-- search_path is pinned to prevent search_path hijacking in a
-- SECURITY DEFINER function (standard Postgres hardening practice).
CREATE SCHEMA IF NOT EXISTS internal;

CREATE OR REPLACE FUNCTION internal.is_household_member(
  p_household_id uuid,
  p_profile_id    uuid,
  p_roles         household_member_role[] DEFAULT NULL
) RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
STABLE
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM household_members hm
    WHERE hm.household_id = p_household_id
      AND hm.profile_id   = p_profile_id
      AND (p_roles IS NULL OR hm.role = ANY(p_roles))
  );
$$;

-- Postgres grants EXECUTE to PUBLIC by default on function creation;
-- revoke it explicitly as defense-in-depth even though the schema
-- relocation above already prevents direct RPC access.
REVOKE EXECUTE ON FUNCTION internal.is_household_member(uuid, uuid, household_member_role[]) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION internal.is_household_member(uuid, uuid, household_member_role[]) TO authenticated;

-- ============================================================
-- contribution_claims RLS policies
-- ============================================================

-- SELECT: any active member of the claim's household may read it.
-- No cross-household read under any condition — household_id membership
-- is the only gate.
CREATE POLICY contribution_claims_select_household_member
ON contribution_claims
FOR SELECT
TO authenticated
USING (
  internal.is_household_member(household_id, auth.uid())
);

-- INSERT: claimant must be an active household member (matches
-- contributions.claim_completed — granted to owner/admin/adult/child in
-- src/domain/permissions.ts; kept as an explicit role list here so a
-- future narrowing of that grant is easy to find and mirror in RLS).
-- May only claim for themselves — claimed_by_profile_id must equal the
-- caller. Must be inserted as an unreviewed pending claim: a modified
-- client cannot self-approve at creation time by inserting status =
-- 'approved' directly, or by pre-filling reviewed_by_profile_id/reviewed_at.
CREATE POLICY contribution_claims_insert_self_pending
ON contribution_claims
FOR INSERT
TO authenticated
WITH CHECK (
  claimed_by_profile_id = auth.uid()
  AND status = 'pending'
  AND reviewed_by_profile_id IS NULL
  AND reviewed_at IS NULL
  AND internal.is_household_member(
    household_id,
    auth.uid(),
    ARRAY['owner','admin','adult','child']::household_member_role[]
  )
);

-- UPDATE: only owner/admin/adult household members may review a claim
-- (matches contributions.approve_claim / contributions.reject_claim —
-- child is deliberately excluded, matching permissions.ts). USING guards
-- the pre-update row: only claims still in status = 'pending' are visible
-- to this policy at all, so an already-approved/rejected claim can never
-- be targeted again — this is the DB-level enforcement of "prevent
-- unauthorized updates of already approved/rejected claims", independent
-- of the app-layer status check in approveContributionClaim/
-- rejectContributionClaim. WITH CHECK guards the resulting row: it must
-- land in a terminal status, and reviewed_by_profile_id must record the
-- actual caller (a reviewer cannot attribute their review to someone else).
CREATE POLICY contribution_claims_update_review
ON contribution_claims
FOR UPDATE
TO authenticated
USING (
  status = 'pending'
  AND internal.is_household_member(
    household_id,
    auth.uid(),
    ARRAY['owner','admin','adult']::household_member_role[]
  )
)
WITH CHECK (
  status IN ('approved', 'rejected')
  AND reviewed_by_profile_id = auth.uid()
  AND internal.is_household_member(
    household_id,
    auth.uid(),
    ARRAY['owner','admin','adult']::household_member_role[]
  )
);

-- No DELETE policy: RLS default-deny blocks all deletes. The app never
-- deletes claims, so no policy is added rather than adding one that's
-- unused scaffolding.

-- ============================================================
-- Duplicate-pending-claim guard (DB level)
-- ============================================================
--
-- At most one pending claim per (household, claimant). Partial unique
-- index — only rows with status = 'pending' participate, so a claimant
-- can freely have any number of approved/rejected claims, just not more
-- than one awaiting review at a time. A second pending INSERT for the
-- same (household_id, claimed_by_profile_id) raises a unique_violation
-- (Postgres error code 23505), which the execution layer maps to a
-- friendly "you already have one pending" result (see
-- src/features/contributions/claimContribution.ts).
CREATE UNIQUE INDEX uq_contribution_claims_one_pending_per_member
  ON contribution_claims (household_id, claimed_by_profile_id)
  WHERE status = 'pending';
