-- T1.7.3: Contribution Claims Foundation
-- ChoreHero — contribution_claims table
--
-- Scope: enum, table, PK/FK, indexes, constraints, RLS enabled.
-- NOT included: RLS policies (deferred, matching the convention set in
-- 20260624000000_initial_schema.sql — policies are added in a dedicated
-- follow-up, not inline with table creation).
-- NOT included: points_balances / point_transactions changes. Points
-- balances only change via SECURITY DEFINER RPCs (see types/supabase.ts
-- comment on points_balances) and no such RPC exists yet — awarding points
-- on claim approval is deferred to the ticket that introduces it.
--
-- Contribution ≠ Task (see docs/household-roles-and-permissions.md):
-- a contribution_claims row is a standalone, self-reported completed
-- action. It is not linked to a tasks row.
--
-- Migration history rule: do not edit this file after it is applied.

CREATE TYPE contribution_claim_status AS ENUM (
  'pending',
  'approved',
  'rejected'
);

-- ------------------------------------------------------------
-- contribution_claims
-- Bottom-up self-reported contributions awaiting household approval.
-- Claim ≠ Completion: a claim only becomes a completion once approved.
-- ------------------------------------------------------------
CREATE TABLE contribution_claims (
  id                     uuid                       PRIMARY KEY DEFAULT gen_random_uuid(),
  household_id           uuid                       NOT NULL REFERENCES households (id) ON DELETE CASCADE,
  title                  text                       NOT NULL,
  description            text                       NULL,
  points                 integer                    NOT NULL DEFAULT 0,
  status                 contribution_claim_status  NOT NULL DEFAULT 'pending',
  claimed_by_profile_id  uuid                       NOT NULL REFERENCES profiles (id) ON DELETE RESTRICT,
  -- RESTRICT: preserve claim history; don't silently remove claims if the claimant's profile is removed
  reviewed_by_profile_id uuid                       NULL     REFERENCES profiles (id) ON DELETE SET NULL,
  reviewed_at            timestamptz                NULL,
  note                   text                       NULL,
  created_at             timestamptz                NOT NULL DEFAULT now(),
  updated_at             timestamptz                NOT NULL DEFAULT now(),

  CONSTRAINT chk_contribution_claims_points_non_negative CHECK (points >= 0)
);

CREATE INDEX idx_contribution_claims_household          ON contribution_claims (household_id);
CREATE INDEX idx_contribution_claims_claimed_by          ON contribution_claims (claimed_by_profile_id);
CREATE INDEX idx_contribution_claims_status              ON contribution_claims (status);
CREATE INDEX idx_contribution_claims_household_status    ON contribution_claims (household_id, status);

ALTER TABLE contribution_claims ENABLE ROW LEVEL SECURITY;
