-- Reward Reserved Points — Slice 2: reservation-aware request RPC +
-- child cancellation RPC.
--
-- Product model change (supersedes the "no reservation at request time"
-- rule from 20260822010000_reward_redemption_rpcs.sql): a reward request
-- now reserves points immediately. points_balances.balance remains the
-- gross/owned total — unchanged in meaning and unchanged by this
-- migration — approve_reward_redemption and reject_reward_redemption
-- (previous migration) need NO functional changes: approval already
-- performs the single, correct permanent-spend deduction from gross
-- balance exactly once (Decision 5, unchanged); rejection already does
-- no balance mutation at all (a reservation was never a real balance
-- write, so releasing one needs no balance write either). Only
-- request_reward_redemption's validation changes, and a new
-- cancel_reward_redemption RPC is added.
--
-- Reservation architecture chosen: DERIVED, not stored. No new column on
-- points_balances. "Reserved" for a given child+household is computed as
-- SUM(points_required_snapshot) over that child's own currently-PENDING
-- reward_redemptions rows — reward_redemptions (RPC-exclusive mutation,
-- already RLS + REVOKE hardened, already the authoritative source for
-- "is there an existing pending request") is already the correct single
-- source of truth for this; storing a second, independently-mutated
-- reserved-amount field would only create a synchronization risk with no
-- offsetting benefit, since every path that would update it already runs
-- inside the same SECURITY DEFINER transaction that mutates
-- reward_redemptions itself.
--
--   available = points_balances.balance - reserved
--   reserved  = SUM(points_required_snapshot) WHERE status = 'pending'
--               AND household_id = X AND requested_by_profile_id = Y
--
-- Migration history rule: do not edit this file after it is applied.

-- ============================================================
-- CHECK constraint: allow the new CANCELLED terminal state
-- ============================================================
--
-- CANCELLED is a child's own withdrawal, not an adult review — it is
-- deliberately grouped with PENDING's reviewer-metadata shape (both
-- NULL), not with APPROVED/REJECTED's (both NOT NULL). Widening only —
-- every existing row already satisfies this constraint unchanged.
ALTER TABLE reward_redemptions
  DROP CONSTRAINT chk_reward_redemptions_review_metadata_consistency;

ALTER TABLE reward_redemptions
  ADD CONSTRAINT chk_reward_redemptions_review_metadata_consistency CHECK (
    (status IN ('pending', 'cancelled') AND reviewed_by_profile_id IS NULL AND reviewed_at IS NULL)
    OR
    (status IN ('approved', 'rejected') AND reviewed_by_profile_id IS NOT NULL AND reviewed_at IS NOT NULL)
  );

-- ============================================================
-- Legacy compatibility marker: reservation_model
-- ============================================================
--
-- The previous Product contract allowed a PENDING redemption with NO
-- points reservation at all. Deploying the reservation-aware
-- request_reward_redemption below must not silently reinterpret an
-- already-existing PENDING row (created under that old contract) as a
-- reservation — doing so would retroactively shrink that child's
-- Available balance with no action of their own.
--
-- Explicit, durable, auditable discriminator — deliberately NOT an
-- inferred heuristic like "created_at before this migration's deploy
-- time" (fragile: clock skew, replayed migrations, backfills). Two-step
-- DEFAULT, not one, and this order matters:
--
--   1. ADD COLUMN ... DEFAULT 'legacy' — classifies every row that
--      already exists at the moment this migration runs. Postgres
--      applies a column's DEFAULT to pre-existing rows as part of adding
--      the column itself (metadata-only, no table rewrite, no backfill
--      UPDATE needed) — this is the ONLY step that touches those rows,
--      and nothing after this point ever rewrites them back to
--      'reserved'.
--   2. ALTER COLUMN ... SET DEFAULT 'reserved' — changes the column's
--      default for INSERTs from this point forward. 'legacy' must never
--      be the resting default: if it were, any future insert path that
--      accidentally omitted reservation_model would silently create a
--      new redemption that bypasses reservation accounting. Every row
--      created after this migration — via request_reward_redemption
--      (which continues to set it explicitly, see below) or via any
--      future insert path that omits it — defaults to 'reserved', the
--      safe choice for anything genuinely new. Changing a column's
--      DEFAULT never touches existing rows' stored values, only what a
--      future bare INSERT receives — so this step cannot retroactively
--      alter the 'legacy' rows step 1 just classified.
--
-- request_reward_redemption continues to set reservation_model =
-- 'reserved' explicitly on every insert (see below) — the column DEFAULT
-- is defense-in-depth for a future/omitted insert path, not a
-- replacement for that explicit RPC contract.
--
-- approve_reward_redemption and reject_reward_redemption need no
-- awareness of this column at all: neither one ever reads the
-- reservation sum — approval always deducts points_required_snapshot
-- directly from gross balance exactly once, rejection never mutates
-- balance at all, regardless of which model produced the row.
-- cancel_reward_redemption likewise needs no awareness of it:
-- cancellation is a pure status transition with no balance mutation, so
-- it is inherently safe for a legacy row (nothing was ever reserved for
-- it, so nothing needs to be "released").
ALTER TABLE reward_redemptions
  ADD COLUMN reservation_model text NOT NULL DEFAULT 'legacy'
  CHECK (reservation_model IN ('legacy', 'reserved'));

ALTER TABLE reward_redemptions
  ALTER COLUMN reservation_model SET DEFAULT 'reserved';

-- ============================================================
-- Index: efficient per-(household, child) pending-reservation sum
-- ============================================================
--
-- Partial (WHERE status = 'pending'), mirroring
-- uq_reward_redemptions_one_pending_per_child_reward's own partial-index
-- convention — small, fast, and never needs to touch resolved rows.
CREATE INDEX idx_reward_redemptions_pending_by_household_child
  ON reward_redemptions (household_id, requested_by_profile_id)
  WHERE status = 'pending';

-- ============================================================
-- request_reward_redemption — now reservation-aware
-- ============================================================
--
-- Only the balance/availability check changes from the original
-- (20260822010000): the FOR SHARE lock on points_balances is upgraded to
-- FOR UPDATE so two concurrent requests by the SAME child (for two
-- DIFFERENT rewards) cannot both read "sufficient available" before
-- either has inserted — the second request blocks until the first's
-- transaction commits or rolls back, then re-reads a now-consistent
-- reserved sum. Different children's requests remain fully concurrent
-- (they lock different points_balances rows). Everything else in this
-- function (idempotency fast-path, reward lock/status/eligibility
-- checks, the insert, and the unique-violation fallback) is unchanged
-- from the original.
CREATE OR REPLACE FUNCTION public.request_reward_redemption(
  p_reward_id         uuid,
  p_client_request_id uuid
)
RETURNS public.reward_redemptions
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_caller           uuid := auth.uid();
  v_existing         public.reward_redemptions%ROWTYPE;
  v_reward_household uuid;
  v_reward_status    reward_status;
  v_reward_price     integer;
  v_balance          integer;
  v_reserved         integer;
  v_available        integer;
  v_redemption       public.reward_redemptions%ROWTYPE;
BEGIN
  IF v_caller IS NULL THEN
    RAISE EXCEPTION 'Not authenticated' USING ERRCODE = '28000';
  END IF;

  SELECT * INTO v_existing
  FROM public.reward_redemptions
  WHERE requested_by_profile_id = v_caller
    AND client_request_id = p_client_request_id;

  IF FOUND THEN
    IF v_existing.reward_id = p_reward_id THEN
      RETURN v_existing;
    ELSE
      RAISE EXCEPTION 'client_request_id already used for a different reward' USING ERRCODE = 'CH010';
    END IF;
  END IF;

  SELECT household_id, status, points_required
    INTO v_reward_household, v_reward_status, v_reward_price
  FROM public.rewards
  WHERE id = p_reward_id
  FOR SHARE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Reward not found' USING ERRCODE = 'CH006';
  END IF;

  IF v_reward_status <> 'active' THEN
    RAISE EXCEPTION 'Reward is not active' USING ERRCODE = 'CH007';
  END IF;

  IF NOT internal.is_household_member(
    v_reward_household, v_caller, ARRAY['child']::household_member_role[]
  ) THEN
    RAISE EXCEPTION 'Not authorized to request this reward' USING ERRCODE = '28000';
  END IF;

  -- FOR UPDATE (not FOR SHARE): serializes concurrent reservation
  -- decisions for this exact child+household — see the function-level
  -- comment above for why this is the correct lock granularity.
  SELECT balance INTO v_balance
  FROM public.points_balances
  WHERE household_id = v_reward_household
    AND profile_id   = v_caller
  FOR UPDATE;

  IF NOT FOUND THEN
    v_balance := 0;
  END IF;

  -- Legacy compatibility: only rows this same RPC itself created
  -- ('reserved') count toward the reservation sum. A PENDING row that
  -- predates the reservation_model column (still 'legacy' by its own
  -- DEFAULT) is excluded here — see this migration's own comment on the
  -- column above for why.
  SELECT COALESCE(SUM(points_required_snapshot), 0) INTO v_reserved
  FROM public.reward_redemptions
  WHERE household_id = v_reward_household
    AND requested_by_profile_id = v_caller
    AND status = 'pending'
    AND reservation_model = 'reserved';

  v_available := v_balance - v_reserved;

  IF v_available < v_reward_price THEN
    RAISE EXCEPTION 'Insufficient available balance to request this reward' USING ERRCODE = 'CH008';
  END IF;

  BEGIN
    INSERT INTO public.reward_redemptions
      (household_id, reward_id, requested_by_profile_id, client_request_id, points_required_snapshot, reservation_model)
    VALUES
      (v_reward_household, p_reward_id, v_caller, p_client_request_id, v_reward_price, 'reserved')
    RETURNING * INTO v_redemption;

    RETURN v_redemption;
  EXCEPTION WHEN unique_violation THEN
    -- Decision 10 has semantic precedence over Decision 8. Re-derive the
    -- outcome from actual row data rather than from which constraint's
    -- name happened to appear in this exception — correct regardless of
    -- Postgres's internal check ordering for this specific conflict.
    SELECT * INTO v_existing
    FROM public.reward_redemptions
    WHERE requested_by_profile_id = v_caller
      AND client_request_id = p_client_request_id;

    IF FOUND THEN
      IF v_existing.reward_id = p_reward_id THEN
        RETURN v_existing;
      ELSE
        RAISE EXCEPTION 'client_request_id already used for a different reward' USING ERRCODE = 'CH010';
      END IF;
    ELSE
      -- No row matches this idempotency key, so the violation must have
      -- been Decision 8's one-pending-per-(child,reward) constraint.
      RAISE EXCEPTION 'A pending redemption already exists for this reward' USING ERRCODE = 'CH011';
    END IF;
  END;
END;
$$;

-- ============================================================
-- cancel_reward_redemption — NEW, child self-service
-- ============================================================
--
-- Mirrors reject_reward_redemption's shape closely (no reward-row lock
-- needed, no balance/ledger mutation — a reservation was never a real
-- balance write, so releasing it is purely the status transition itself)
-- but with a different authorization rule: the caller must BE the
-- redemption's own requester, not a household owner/admin/adult.
-- reviewed_by_profile_id/reviewed_at are deliberately left NULL — this
-- is the child withdrawing their own request, not an adult review.
CREATE OR REPLACE FUNCTION public.cancel_reward_redemption(
  p_redemption_id uuid
)
RETURNS public.reward_redemptions
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_caller     uuid := auth.uid();
  v_redemption public.reward_redemptions%ROWTYPE;
BEGIN
  IF v_caller IS NULL THEN
    RAISE EXCEPTION 'Not authenticated' USING ERRCODE = '28000';
  END IF;

  SELECT * INTO v_redemption
  FROM public.reward_redemptions
  WHERE id = p_redemption_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Redemption not found' USING ERRCODE = 'CH012';
  END IF;

  IF v_redemption.requested_by_profile_id <> v_caller THEN
    RAISE EXCEPTION 'Not authorized to cancel this redemption' USING ERRCODE = '28000';
  END IF;

  UPDATE public.reward_redemptions
  SET status     = 'cancelled',
      updated_at = now()
  WHERE id = p_redemption_id
    AND status = 'pending'
  RETURNING * INTO v_redemption;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Redemption is not pending' USING ERRCODE = 'CH013';
  END IF;

  RETURN v_redemption;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.cancel_reward_redemption(uuid) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION public.cancel_reward_redemption(uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.cancel_reward_redemption(uuid) FROM anon;
