-- Fixes createHouseholdWithOwner (src/lib/repositories/households.ts) failing
-- on every call in production.
--
-- Root cause: households.ts inserts the household row with
-- `.insert({...}).select('*').single()`. Postgres RLS applies the table's
-- SELECT policy (USING clause) to the RETURNING output of an INSERT, not
-- just the INSERT policy's WITH CHECK. households_select_member (from
-- 20260707000000_core_rls_policies.sql) only allows rows where the caller
-- is already a household_members row for that household:
--
--   USING ( internal.is_household_member(id, auth.uid()) )
--
-- At the moment the household INSERT runs, no household_members row exists
-- yet — that is only inserted in the following step, once the household id
-- is known. So the newly inserted row never passes the SELECT policy,
-- RETURNING yields zero rows, and the client's .single() call throws "no
-- rows returned" on every single household creation, even though
-- WITH CHECK (created_by_profile_id = auth.uid()) on the INSERT policy
-- passes and the row is actually committed (orphaned — matches the
-- "atomicity" risk already called out in households.ts's own comments).
--
-- Fix: let the creator see a household they created regardless of
-- membership-row timing. This does not widen access beyond what already
-- happens moments later anyway (createHouseholdWithOwner always inserts the
-- creator as the 'owner' member immediately after), so this is not a
-- meaningful new exposure — it just removes a race against that follow-up
-- insert.
--
-- Migration history rule: do not edit this file after it is applied.

DROP POLICY households_select_member ON households;

CREATE POLICY households_select_member
ON households
FOR SELECT
TO authenticated
USING (
  created_by_profile_id = auth.uid()
  OR internal.is_household_member(id, auth.uid())
);
