-- Fixes a confirmed defect: a household member who both submits a
-- Contribution Claim and holds contributions.approve_claim/reject_claim
-- (owner/admin/adult — contributions.claim_completed is granted to every
-- role, see src/domain/permissions.ts) could review — approve OR reject —
-- their own claim. Neither the existing UI (ContributionReviewSection),
-- the existing application layer (approveContributionClaim.ts /
-- rejectContributionClaim.ts), nor this table's RLS policy previously
-- excluded the claimant from being their own reviewer.
--
-- Scope: this migration only. No new table, no new RPC, no permission-
-- model or household-membership semantics change. Every existing
-- authorization condition on contribution_claims_update_review is
-- preserved verbatim; the only addition is "the reviewer is not the
-- claimant."
--
-- Mutation path (confirmed by reading src/lib/repositories/
-- contributionClaims.ts): approve/reject go through a direct PostgREST
-- UPDATE on contribution_claims, not an RPC. This RLS policy is therefore
-- the authoritative enforcement boundary for this defect — the
-- application-layer checks added alongside this migration (see
-- approveContributionClaim.ts / rejectContributionClaim.ts) are
-- defense-in-depth, not the primary boundary.
--
-- Identity model (see docs/rls-strategy.md §2 and
-- supabase/migrations/20260624000000_initial_schema.sql: profiles.id
-- PRIMARY KEY REFERENCES auth.users(id)): profiles.id and auth.uid() are
-- the same identity value for a given user, by a 1:1 FK, not an
-- assumption. contribution_claims_insert_self_pending (below, unchanged)
-- already requires claimed_by_profile_id = auth.uid() at INSERT time, so
-- every claim's claimant is, by construction, whoever created it.
--
-- Bypass class closed by this exact fix: the previous policy's WITH CHECK
-- constrained status/reviewed_by_profile_id/membership but never
-- constrained claimed_by_profile_id, so a direct PostgREST caller could in
-- principle submit an UPDATE that also rewrites claimed_by_profile_id in
-- the same statement as the review action. Postgres evaluates a FOR
-- UPDATE policy's USING clause against the pre-update row and WITH CHECK
-- against the resulting row — adding "claimed_by_profile_id <> auth.uid()"
-- to both closes both directions:
--   USING:      a claim already belonging to the caller is not even
--               visible for update, regardless of what they try to set
--               claimed_by_profile_id to.
--   WITH CHECK: a caller cannot land a row where claimed_by_profile_id
--               ends up equal to themselves either — so reassigning
--               someone else's pending claim to themselves while
--               reviewing it is also rejected.
-- No trigger is added — this is achievable entirely within the existing
-- USING/WITH CHECK mechanism already used by this policy, and no trigger
-- exists on this table today (confirmed: no CREATE TRIGGER references
-- contribution_claims anywhere in supabase/migrations/).
--
-- Migration history rule: do not edit this file after it is applied.

DROP POLICY contribution_claims_update_review ON contribution_claims;

CREATE POLICY contribution_claims_update_review
ON contribution_claims
FOR UPDATE
TO authenticated
USING (
  status = 'pending'
  AND claimed_by_profile_id <> auth.uid()
  AND internal.is_household_member(
    household_id,
    auth.uid(),
    ARRAY['owner','admin','adult']::household_member_role[]
  )
)
WITH CHECK (
  status IN ('approved', 'rejected')
  AND claimed_by_profile_id <> auth.uid()
  AND reviewed_by_profile_id = auth.uid()
  AND internal.is_household_member(
    household_id,
    auth.uid(),
    ARRAY['owner','admin','adult']::household_member_role[]
  )
);
