-- Rewards Redemption — Slice 1: schema foundation.
-- See docs/adr-001-family-member-identity-model.md's own convention: this
-- migration record does not restate the full product/security rationale
-- already captured in the approved design conversation — only what a
-- future reader needs to understand the schema itself.
--
-- Scope: enum, reward_redemptions table, RLS (SELECT-only — no INSERT/
-- UPDATE/DELETE policy exists; combined with the explicit REVOKE below,
-- every mutation of this table is only reachable through the
-- SECURITY DEFINER RPCs added in the next migration), constraints,
-- indexes, and one additive column + constraint on the existing
-- point_transactions table for redemption-to-ledger audit correlation.
--
-- Product model (Decisions 1-11, locked): request/approval workflow —
-- a child requests a reward (PENDING, no points moved), an adult/admin/
-- owner approves (atomic balance deduction + ledger entry) or rejects
-- (no balance change). No self-redemption. No adult-initiated requests
-- on behalf of a child (requester = beneficiary = child, always). At
-- most one PENDING redemption per (child, reward). Balance required at
-- request time using a request-time price snapshot, never re-read at
-- approval. True idempotency via a client-generated client_request_id.
-- SELECT visibility is self-or-adult+.
--
-- Migration history rule: do not edit this file after it is applied.

-- ============================================================
-- reward_redemption_status
-- ============================================================

CREATE TYPE reward_redemption_status AS ENUM (
  'pending',
  'approved',
  'rejected'
);

-- ============================================================
-- reward_redemptions
-- ============================================================
--
-- requested_by_profile_id doubles as the beneficiary — Decision 4 makes
-- requester and beneficiary the same profile always, so a single column
-- is sufficient (no separate "beneficiary_profile_id").
--
-- client_request_id: client-generated UUID, one per intentional user
-- action, reused verbatim across automatic retries of that same action.
-- Uniqueness is scoped to (requested_by_profile_id, client_request_id)
-- rather than globally — profiles.id is already a globally unique
-- identity (profiles.id REFERENCES auth.users(id)), so per-requester
-- scoping is sufficient and avoids any cross-household/cross-user
-- collision concern without adding a redundant household_id column to
-- this specific constraint.
--
-- points_required_snapshot: captured once, at request time, from the
-- reward's points_required at that moment (Decision 6) — authoritative
-- for the entire redemption regardless of any later price change.
CREATE TABLE reward_redemptions (
  id                     uuid                       PRIMARY KEY DEFAULT gen_random_uuid(),
  household_id           uuid                       NOT NULL REFERENCES households (id) ON DELETE CASCADE,
  reward_id              uuid                       NOT NULL REFERENCES rewards (id) ON DELETE RESTRICT,
  -- RESTRICT: a reward with redemption history should not be silently
  -- deletable — mirrors rewards.created_by_profile_id's own "preserve
  -- history" RESTRICT rationale, applied here because rewards CAN be
  -- deleted today (rewards_delete_admin_plus) and reward_id is NOT NULL,
  -- so SET NULL is not an option without changing that nullability.
  requested_by_profile_id uuid                      NOT NULL REFERENCES profiles (id) ON DELETE RESTRICT,
  -- RESTRICT: preserve redemption history; mirrors
  -- contribution_claims.claimed_by_profile_id exactly.
  client_request_id      uuid                       NOT NULL,
  points_required_snapshot integer                  NOT NULL,
  status                 reward_redemption_status  NOT NULL DEFAULT 'pending',
  reviewed_by_profile_id uuid                       NULL REFERENCES profiles (id) ON DELETE SET NULL,
  reviewed_at            timestamptz                NULL,
  requested_at           timestamptz                NOT NULL DEFAULT now(),
  created_at             timestamptz                NOT NULL DEFAULT now(),
  updated_at             timestamptz                NOT NULL DEFAULT now(),

  CONSTRAINT chk_reward_redemptions_points_positive CHECK (points_required_snapshot > 0),

  -- Defense-in-depth: the three authoritative RPCs (next migration)
  -- already guarantee this by construction (INSERT never sets reviewer
  -- fields; approve/reject always set both together) — this CHECK adds
  -- no new correctness guarantee given RPC-exclusive mutation, but
  -- catches a future bug in the RPC bodies themselves at negligible cost.
  CONSTRAINT chk_reward_redemptions_review_metadata_consistency CHECK (
    (status = 'pending' AND reviewed_by_profile_id IS NULL AND reviewed_at IS NULL)
    OR
    (status IN ('approved', 'rejected') AND reviewed_by_profile_id IS NOT NULL AND reviewed_at IS NOT NULL)
  ),

  -- Decision 10 (true idempotency) — permanent, not status-scoped, so the
  -- guarantee survives a PENDING -> APPROVED/REJECTED transition. This is
  -- deliberately a different mechanism from the partial index below.
  CONSTRAINT uq_reward_redemptions_idempotency_key UNIQUE (requested_by_profile_id, client_request_id)
);

CREATE INDEX idx_reward_redemptions_household           ON reward_redemptions (household_id);
CREATE INDEX idx_reward_redemptions_requested_by         ON reward_redemptions (requested_by_profile_id);
CREATE INDEX idx_reward_redemptions_status               ON reward_redemptions (status);
CREATE INDEX idx_reward_redemptions_household_status     ON reward_redemptions (household_id, status);
CREATE INDEX idx_reward_redemptions_reward               ON reward_redemptions (reward_id);

-- Decision 8 (at most one PENDING redemption per (child, reward)) —
-- partial, so it stops applying once a redemption leaves 'pending'.
-- Mirrors uq_contribution_claims_one_pending_per_member exactly,
-- extended by reward_id.
CREATE UNIQUE INDEX uq_reward_redemptions_one_pending_per_child_reward
  ON reward_redemptions (household_id, reward_id, requested_by_profile_id)
  WHERE status = 'pending';

ALTER TABLE reward_redemptions ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- Privilege boundary: table privileges + RLS, both required
-- ============================================================
--
-- Layer 1 — table privileges: no INSERT/UPDATE/DELETE grant to anon or
-- authenticated at all. Layer 2 — RLS: enabled, with a SELECT policy
-- only (below). Combined, there is no client-write path of any kind;
-- the only way to mutate this table is a SECURITY DEFINER RPC (next
-- migration), which runs as its owner and bypasses both layers by
-- Postgres's own SECURITY DEFINER semantics — not a third RLS-like
-- layer, the sanctioned exception to the two denial layers above.
REVOKE INSERT, UPDATE, DELETE ON reward_redemptions FROM anon, authenticated;

-- Decision 11 (SELECT visibility = self-or-adult+) — mirrors
-- points_balances_select_self_or_adult_plus /
-- point_transactions_select_self_or_adult_plus exactly, not the
-- household-wide pattern used by tasks/contribution_claims: a
-- redemption carries per-child economic data, matching why points
-- tables chose the narrower visibility model.
CREATE POLICY reward_redemptions_select_self_or_adult_plus
ON reward_redemptions
FOR SELECT
TO authenticated
USING (
  requested_by_profile_id = auth.uid()
  OR internal.is_household_member(household_id, auth.uid(), ARRAY['owner','admin','adult']::household_member_role[])
);

-- No INSERT/UPDATE/DELETE policy: RLS default-deny handles those, with
-- the explicit REVOKE above as an independent second layer against the
-- same client-write path. No DELETE policy or grant of any kind exists —
-- this table is never deleted from by any code, matching
-- contribution_claims' own "no DELETE policy, app never deletes"
-- convention.

-- ============================================================
-- point_transactions: redemption-to-ledger audit correlation
-- ============================================================
--
-- reward_id alone cannot identify a specific redemption cycle once
-- repeated redemption of the same reward is allowed (Decision 3) — two
-- approved redemptions of the same reward by the same child would
-- otherwise be indistinguishable via reward_id. This additive column
-- closes that gap. Nullable: every existing transaction type
-- (task_completed, manual_adjustment, correction) leaves it NULL: a
-- plain UNIQUE constraint permits unlimited NULLs in Postgres, so this
-- does not disturb any existing transaction type.
--
-- ON DELETE RESTRICT (not the SET NULL used by this table's own
-- reward_id/task_id columns): those reference entities with real,
-- currently-existing delete paths (rewards_delete_admin_plus). No DELETE
-- policy exists anywhere for reward_redemptions in this migration, so
-- this FK's ON DELETE behavior describes an unreachable event under the
-- current design — RESTRICT is the conservative, audit-preserving
-- default per this schema's own established "preserve X, don't silently
-- orphan history" pattern (rewards.created_by_profile_id ON DELETE
-- RESTRICT), rather than inventing a SET NULL requirement with no
-- present justification.
ALTER TABLE point_transactions
  ADD COLUMN reward_redemption_id uuid NULL REFERENCES reward_redemptions (id) ON DELETE RESTRICT;

-- Enforces "at most one ledger event per approved redemption" as a
-- database-level invariant, not merely an application convention.
-- Nothing in the locked Product Decisions defines a reversal/correction
-- workflow for a redemption, so exactly one row per redemption is
-- correct for the currently-approved scope.
ALTER TABLE point_transactions
  ADD CONSTRAINT uq_point_transactions_reward_redemption UNIQUE (reward_redemption_id);

CREATE INDEX idx_point_txn_reward_redemption ON point_transactions (reward_redemption_id);
